import { defineQuestions } from '../define.js';

/**
 * Terminology spot-checks based on the ISTQB Glossary
 * (https://glossary.istqb.org). Terminology is graded by how far into a career
 * the term normally appears, not by how long the definition is.
 *
 * These questions deliberately test the DISTINCTION between neighbouring terms
 * (defect vs failure, retesting vs regression, driver vs stub), because that is
 * where imprecise vocabulary actually costs a team time in a stand-up.
 */

export const glossaryTraineeQuestions = defineQuestions('trainee', 'istqb-glossary', [
  ['GL-T-001', 'defect-lifecycle',
    'ISTQB Glossary: which term means "an event in which a component or system does not perform a required function within specified limits"?',
    ['Failure', 'Defect', 'Error', 'Mistake'], 0,
    'Failure is the observed event. Defect is the flaw in the work product; error is the human action that produced it.'],
  ['GL-T-002', 'defect-lifecycle',
    'ISTQB Glossary: a "defect" is best defined as:',
    ['An imperfection in a work product that may cause it to fail to meet its requirements', 'The observed incorrect behaviour', 'A human action producing an incorrect result', 'A failed test case'], 0,
    'A defect can exist for years without ever causing a failure, if the code path is never executed with the triggering data.'],
  ['GL-T-003', 'test-artifacts',
    'ISTQB Glossary: a "test case" consists of:',
    ['Preconditions, inputs, actions, expected results and postconditions', 'A list of features to test', 'A summary of testing performed', 'The schedule for a test level'], 0,
    'The postcondition is the part most often omitted, and its absence is why cases leave the system in a state that breaks the next case.'],
  ['GL-T-004', 'testing-types',
    'ISTQB Glossary: "retesting" (confirmation testing) means:',
    ['Testing that runs test cases that failed the last time, to verify a fix', 'Testing unchanged areas after a change', 'Running the whole suite again', 'Testing by a second tester'], 0,
    'Retesting targets the fix; regression testing targets the neighbourhood of the fix.'],
  ['GL-T-005', 'test-execution',
    'ISTQB Glossary: "test execution" is:',
    ['The process of running a test on the component or system under test', 'The process of designing tests', 'The process of writing a test plan', 'The process of reporting defects'], 0,
    'Execution produces actual results, which are then compared with the expected results.'],
  ['GL-T-006', 'test-documentation',
    'ISTQB Glossary: a "test condition" is:',
    ['A testable aspect of a component or system identified as a basis for testing', 'A precondition of a test case', 'The environment configuration', 'A defect status'], 0,
    'Test conditions are the output of test analysis; test cases are the output of test design.'],
  ['GL-T-007', 'test-artifacts',
    'ISTQB Glossary: "test data" is:',
    ['Data created or selected to satisfy the input requirements for executing tests', 'The output of a test', 'The test results', 'The defect log'], 0,
    'Test data management is one of the largest hidden costs in a mature test process.'],
  ['GL-T-008', 'testing-types',
    'ISTQB Glossary: which term describes "testing to determine the ease with which users can learn to use a product"?',
    ['Learnability testing', 'Usability testing in general', 'Accessibility testing', 'Operability testing'], 0,
    'Learnability, operability, user error protection and accessibility are all sub-characteristics under usability in ISO 25010.'],
  ['GL-T-009', 'test-execution',
    'ISTQB Glossary: a "test suite" is:',
    ['A set of test cases or test procedures to be executed in a specific context', 'A tool that runs tests', 'A report of results', 'A single test case'], 0,
    'A suite is the unit of scheduling and reporting; a case is the unit of verdict.'],
  ['GL-T-010', 'test-artifacts',
    'ISTQB Glossary: the "test basis" is:',
    ['The body of knowledge used as the basis for test analysis and design', 'The test environment', 'The set of test data', 'The test management tool'], 0,
    'Requirements, designs, code, risk analyses and even experience can all serve as a test basis.'],
  ['GL-T-011', 'severity-priority',
    'ISTQB Glossary: "priority" of a defect refers to:',
    ['The level of business importance assigned to fixing it', 'The degree of impact on the system', 'How often it occurs', 'How hard it is to fix'], 0,
    'Severity is impact; priority is urgency. The two are set by different people for different reasons.'],
  ['GL-T-012', 'testing-types',
    'ISTQB Glossary: "smoke test" is:',
    ['A subset of tests covering the main functionality to decide whether the build is testable', 'An exhaustive test of one module', 'A test of error handling', 'A test executed by the customer'], 0,
    'It is a gate, not a quality assessment. A build that passes smoke has earned a day of testing, nothing more.'],
  ['GL-T-013', 'test-documentation',
    'ISTQB Glossary: "coverage" is:',
    ['The degree to which specified coverage items are exercised by a test suite', 'The number of test cases', 'The percentage of defects found', 'The size of the test basis'], 0,
    'Coverage is always relative to a stated coverage item: statements, branches, requirements, risks.'],
  ['GL-T-014', 'testing-types',
    'ISTQB Glossary: "regression" refers to:',
    ['Degradation of previously working functionality caused by a change', 'A defect found in a new feature', 'A performance decrease under load', 'A failed deployment'], 0,
    'The word names the phenomenon; regression testing is the activity that looks for it.'],
  ['GL-T-015', 'defect-lifecycle',
    'ISTQB Glossary: "root cause" is:',
    ['A source of a defect such that removing it prevents recurrence of that defect type', 'The failing line of code', 'The first symptom observed', 'The developer who introduced it'], 0,
    'The definition itself contains the test of a real root cause: removing it must stop the class from recurring.'],
]);

export const glossaryJuniorQuestions = defineQuestions('junior', 'istqb-glossary', [
  ['GL-J-001', 'testing-levels',
    'ISTQB Glossary: a "test driver" is:',
    ['A temporary component that replaces a calling component in order to invoke the code under test', 'A component that replaces a called component', 'A tool that manages test data', 'The person executing the tests'], 0,
    'A driver calls down into the unit; a stub stands in for what the unit calls. Confusing them makes integration discussions circular.'],
  ['GL-J-002', 'testing-levels',
    'ISTQB Glossary: a "stub" is:',
    ['A skeletal implementation of a called component used during integration testing', 'A component that invokes the code under test', 'A tool for load generation', 'A defect report template'], 0,
    'Stubs let a component be tested before its dependencies exist, which is what makes top-down integration possible.'],
  ['GL-J-003', 'verification-validation',
    'ISTQB Glossary: "validation" is confirmation that:',
    ['Requirements for a specific intended use or application have been fulfilled', 'A work product matches its specification', 'The code compiles', 'A defect has been fixed'], 0,
    'Verification checks conformity to a specification; validation checks fitness for the intended use.'],
  ['GL-J-004', 'testing-phases-goals',
    'ISTQB Glossary: a "test oracle" is:',
    ['A source to determine the expected result of a test', 'A tool that generates test data', 'A defect prediction model', 'A test management system'], 0,
    'When no oracle exists, testing degrades into observing behaviour without being able to judge it - the oracle problem.'],
  ['GL-J-005', 'testing-levels',
    'ISTQB Glossary: "test harness" means:',
    ['A test environment comprising stubs and drivers needed to execute a test', 'The test management tool', 'The defect tracker', 'The CI server'], 0,
    'The harness is what makes a component executable outside its real surroundings.'],
  ['GL-J-006', 'testing-types',
    'ISTQB Glossary: "maintenance testing" is testing:',
    ['A modified operational system, or the impact of a changed environment on it', 'Of a system still in development', 'Performed by the maintenance team only', 'Of the test environment'], 0,
    'It covers changes, migrations, retirements and environment upgrades, and it always includes regression testing.'],
  ['GL-J-007', 'testing-types',
    'ISTQB Glossary: "alpha testing" is performed:',
    ['At the developing organisation site, but not by the development team', 'At the customer site by real users', 'By the development team only', 'Automatically in CI'], 0,
    'Beta testing is the same idea moved to the customer environment and audience.'],
  ['GL-J-008', 'test-design-techniques',
    'ISTQB Glossary: an "equivalence partition" is:',
    ['A subset of the value domain processed in the same way by the component', 'A group of test cases', 'A set of boundary values', 'A defect category'], 0,
    'The partition is defined by the processing, not by the data type - which is why partitions can cross type boundaries.'],
  ['GL-J-009', 'testing-metrics',
    'ISTQB Glossary: "exit criteria" are:',
    ['Conditions for officially completing a defined task', 'Conditions for starting testing', 'The definition of a defect', 'The test schedule'], 0,
    'Entry criteria gate the start, exit criteria gate the finish. Both must be agreed with the people who will invoke them.'],
  ['GL-J-010', 'defect-management-systems',
    'ISTQB Glossary: "incident" (or anomaly) refers to:',
    ['Any event occurring that requires investigation', 'A confirmed defect', 'A test failure only', 'A production outage only'], 0,
    'An incident may turn out to be a defect, a test error, an environment problem or expected behaviour.'],
  ['GL-J-011', 'testing-types',
    'ISTQB Glossary: "white-box testing" derives tests from:',
    ['The internal structure or implementation of the test object', 'The specification only', 'The tester experience', 'The defect history'], 0,
    'Black-box derives from external descriptions; experience-based derives from knowledge and intuition.'],
  ['GL-J-012', 'sdlc-methodologies',
    'ISTQB Glossary: "shift left" is:',
    ['An approach performing testing and quality activities earlier in the lifecycle', 'Moving tests to another team', 'Reducing test scope', 'Testing in production'], 0,
    'It covers requirement reviews, static analysis, TDD and early integration, not just "test sooner".'],
  ['GL-J-013', 'testing-levels',
    'ISTQB Glossary: "component testing" is also known as:',
    ['Unit testing or module testing', 'System testing', 'Acceptance testing', 'Integration testing'], 0,
    'The three names describe the same test level; different communities inherited different vocabulary.'],
  ['GL-J-014', 'risks-in-testing',
    'ISTQB Glossary: "risk" is:',
    ['A factor that could result in future negative consequences', 'A defect found in testing', 'A failed test case', 'An open incident'], 0,
    'The definition is future-oriented, which is what separates a risk from an issue that has already occurred.'],
  ['GL-J-015', 'testing-phases-goals',
    'ISTQB Glossary: "quality assurance" focuses on:',
    ['Providing confidence that quality requirements will be fulfilled, through process', 'Finding defects in the product', 'Executing test cases', 'Fixing defects'], 0,
    'QA is process-oriented and preventive; testing (quality control) is product-oriented and detective.'],
]);

export const glossaryMiddleQuestions = defineQuestions('middle', 'istqb-glossary', [
  ['GL-M-001', 'testing-metrics',
    'ISTQB Glossary: "defect density" is:',
    ['The number of defects per size unit of the work product', 'The number of defects per tester', 'The rate at which defects are fixed', 'The proportion of defects found before release'], 0,
    'Normalising by size is what makes two modules comparable; the proportion found before release is defect detection percentage.'],
  ['GL-M-002', 'risks-in-testing',
    'ISTQB Glossary: "risk level" is determined by:',
    ['The combination of risk likelihood and risk impact', 'The number of affected requirements', 'The severity of related defects', 'The time to fix'], 0,
    'Both factors are required; either alone produces a ranking that misallocates effort.'],
  ['GL-M-003', 'auto-performance',
    'ISTQB Glossary: "load testing" evaluates behaviour under:',
    ['Anticipated conditions of varying load, usually between expected and peak', 'Conditions beyond the specified limits', 'Sustained load over a long period', 'Sudden extreme spikes'], 0,
    'Beyond the limits is stress testing; long duration is endurance; sudden jumps are spike testing.'],
  ['GL-M-004', 'auto-web-ui',
    'ISTQB Glossary: "test automation" is:',
    ['The use of software to perform or support test activities', 'Writing test scripts only', 'Running tests in CI only', 'Recording and replaying user actions'], 0,
    'The definition covers management, generation, execution and reporting - not just script execution.'],
  ['GL-M-005', 'process-analysis',
    'ISTQB Glossary: "root cause analysis" is:',
    ['An analysis technique to identify the causes of defects in order to prevent recurrence', 'A method to prioritise defects', 'A technique to estimate effort', 'A way to classify severity'], 0,
    'Prevention of recurrence, not explanation of one incident, is the stated purpose.'],
  ['GL-M-006', 'testing-metrics',
    'ISTQB Glossary: "test progress report" is produced:',
    ['Periodically during testing, to summarise status against the plan', 'Only at the end of testing', 'Only when defects are found', 'Only for regulated projects'], 0,
    'The end-of-testing document is the test completion (summary) report, which is a different artefact.'],
  ['GL-M-007', 'testing-types',
    'ISTQB Glossary: "reliability" is the degree to which a system:',
    ['Performs specified functions under specified conditions for a specified period', 'Responds quickly', 'Is easy to use', 'Can be moved between environments'], 0,
    'Reliability sub-characteristics include maturity, availability, fault tolerance and recoverability.'],
  ['GL-M-008', 'test-design-techniques',
    'ISTQB Glossary: "error guessing" is:',
    ['A technique in which experience is used to anticipate defects', 'A structural coverage technique', 'A formal specification-based technique', 'A defect prioritisation method'], 0,
    'It is a recognised experience-based technique, most effective when combined with a defect taxonomy.'],
  ['GL-M-009', 'test-plan',
    'ISTQB Glossary: "test strategy" describes:',
    ['The generalised approach to testing, usually at organisation or programme level', 'The schedule of a single test level', 'The list of test cases', 'The environment configuration'], 0,
    'The project-specific instantiation is the test plan; the reason for testing at all is the test policy.'],
  ['GL-M-010', 'defect-management-systems',
    'ISTQB Glossary: "defect triage" is:',
    ['The process of assessing, prioritising and assigning reported defects', 'The process of fixing defects', 'The process of reproducing defects', 'The process of closing defects'], 0,
    'Triage brings the roles with the necessary context together so priority reflects business reality.'],
  ['GL-M-011', 'testing-types',
    'ISTQB Glossary: "portability" is the degree to which a system:',
    ['Can be transferred from one environment to another', 'Recovers from faults', 'Protects data', 'Uses resources efficiently'], 0,
    'Adaptability, installability and replaceability are its sub-characteristics.'],
  ['GL-M-012', 'process-optimization',
    'ISTQB Glossary: "test process improvement" refers to:',
    ['A programme to improve the quality and efficiency of testing activities', 'Adding more test cases', 'Buying a new test tool', 'Increasing the size of the test team'], 0,
    'TMMi and TPI Next are the two most widely used reference models for it.'],
  ['GL-M-013', 'api-theory',
    'ISTQB Glossary: "API testing" is:',
    ['Testing performed by submitting commands to the interfaces of the test object', 'Testing the UI of an application', 'Testing the database schema', 'Testing network throughput'], 0,
    'It is a test approach defined by the interface used, not by a particular test level.'],
  ['GL-M-014', 'testing-metrics',
    'ISTQB Glossary: "test completion report" (test summary report) is:',
    ['A report summarising test activities and results, produced at a milestone', 'A daily status update', 'The test plan', 'A defect report'], 0,
    'It is the artefact that carries residual risk and lessons learned into the next release.'],
  ['GL-M-015', 'virtualization',
    'ISTQB Glossary: "service virtualization" enables:',
    ['Testing components that depend on unavailable or hard-to-access services', 'Faster CI builds only', 'Running tests on virtual machines', 'Automated deployment'], 0,
    'It removes third-party availability from the critical path of a test environment.'],
]);
