import { defineQuestions } from '../define.js';

/**
 * Junior tier, sourced from the "green" rows of the Performance Review sheet.
 */
export const juniorPrQuestions = defineQuestions('junior', 'pr-matrix', [
  // --- verification-validation --------------------------------------------
  ['JR-VV-001', 'verification-validation',
    'Verification answers which question?',
    ['Are we building the product right?', 'Are we building the right product?', 'Is the product profitable?', 'Is the product fast enough?'], 0,
    'Verification checks the product against its specification. Validation checks it against the real user need - a product can pass verification completely and still be the wrong product.'],
  ['JR-VV-002', 'verification-validation',
    'Which activity is validation rather than verification?',
    ['User acceptance testing with real users on real scenarios', 'A requirements review', 'A code inspection', 'Checking a design document against the spec'], 0,
    'Validation involves the actual need and the actual user. Reviews and inspections compare an artefact against another artefact, which is verification.'],
  ['JR-VV-003', 'verification-validation',
    'A feature matches the specification exactly, but users cannot complete their task with it. This is:',
    ['A validation failure', 'A verification failure', 'Not a defect at all', 'A performance defect'], 0,
    'The build is right; the requirement was wrong. This is precisely the failure mode that validation activities exist to catch, and it should be reported, not dismissed.'],
  ['JR-VV-004', 'verification-validation',
    'Which pair of activities are both verification?',
    ['Static analysis and a design review', 'Beta testing and a design review', 'User acceptance testing and static analysis', 'Beta testing and alpha testing'], 0,
    'Both compare an artefact to its specification without involving the end user need.'],

  // --- acceptance-criteria ------------------------------------------------
  ['JR-AC-001', 'acceptance-criteria',
    'Acceptance criteria for a user story should be:',
    ['Testable, unambiguous and agreed before development starts', 'Written by the tester after the demo', 'As general as possible to allow flexibility', 'Optional for small stories'], 0,
    'Criteria agreed up front are a shared definition of done for that story. Criteria written afterwards describe what was built, which is not the same thing.'],
  ['JR-AC-002', 'acceptance-criteria',
    'What is the difference between acceptance criteria and the Definition of Done?',
    ['Criteria are per story; the DoD applies to every story in the team', 'They are two names for the same thing', 'The DoD is written by the customer only', 'Criteria apply only to bugs'], 0,
    'The DoD is the team-wide quality bar (code reviewed, tests written, deployed to staging). Acceptance criteria describe what this particular story must do.'],
  ['JR-AC-003', 'acceptance-criteria',
    'Which acceptance criterion is untestable as written?',
    ['The page should load reasonably fast', 'The page loads within 2 seconds on a 4G connection', 'An error message is shown when the email is invalid', 'The user is redirected to /dashboard after login'], 0,
    '"Reasonably fast" has no oracle. A criterion that two people can read differently will be disputed at exactly the wrong moment.'],
  ['JR-AC-004', 'acceptance-criteria',
    'A story is demoed and works, but the team has not written the automated tests its DoD requires. The story is:',
    ['Not done', 'Done, since it works', 'Done, if the customer approves', 'Done, but with a follow-up ticket'], 0,
    'The DoD is binary and team-wide. Allowing exceptions turns it into a suggestion, and the debt accumulates silently.'],
  ['JR-AC-005', 'acceptance-criteria',
    'Given/When/Then is a common format for acceptance criteria because it:',
    ['Forces a precondition, an action and an observable outcome', 'Is required by Scrum', 'Makes stories shorter', 'Can only be used with automation tools'], 0,
    'The three clauses map directly onto precondition, step and expected result, which is why they translate so cleanly into test cases.'],

  // --- testing-phases-goals -----------------------------------------------
  ['JR-PH-001', 'testing-phases-goals',
    'Which is NOT a typical goal of testing?',
    ['Proving that the software has no defects', 'Finding defects', 'Reducing risk', 'Providing information for decision making'], 0,
    'Testing can show the presence of defects but never their absence. A goal stated as "prove there are no bugs" is unachievable by definition.'],
  ['JR-PH-002', 'testing-phases-goals',
    'In the fundamental test process, which activity comes immediately after test planning?',
    ['Test monitoring and control, running alongside analysis and design', 'Test execution', 'Test closure', 'Defect reporting'], 0,
    'ISTQB v4 lists planning, monitoring and control, analysis, design, implementation, execution and completion. Monitoring and control runs continuously from planning onward.'],
  ['JR-PH-003', 'testing-phases-goals',
    'Test closure activities include:',
    ['Collecting lessons learned and archiving testware', 'Writing the first test cases', 'Setting up the environment', 'Executing the regression suite'], 0,
    'Closure is where the team converts the experience into something reusable. Skipping it means paying to learn the same lesson next release.'],
  ['JR-PH-004', 'testing-phases-goals',
    'Why is early testing (shift left) valuable?',
    ['Defects found in requirements cost far less to fix than defects found in production', 'It reduces the number of testers needed', 'It removes the need for regression testing', 'It guarantees on-time delivery'], 0,
    'The cost of a defect rises steeply with the phase in which it is found, which is why review of requirements is among the highest-return testing activities.'],

  // --- sdlc-methodologies -------------------------------------------------
  ['JR-SDLC-001', 'sdlc-methodologies',
    'In the V-model, which test level corresponds to the requirements specification?',
    ['Acceptance testing', 'Unit testing', 'Integration testing', 'Component testing'], 0,
    'The V-model pairs each development artefact with the test level that validates it. Requirements pair with acceptance; detailed design pairs with unit/component.'],
  ['JR-SDLC-002', 'sdlc-methodologies',
    'A key characteristic of Scrum is:',
    ['Fixed-length iterations delivering a potentially shippable increment', 'A single test phase after all development', 'No requirements documentation of any kind', 'A dedicated QA sign-off gate between phases'], 0,
    'The sprint boundary and the increment are the two structural commitments of Scrum. Testing happens inside the sprint, not after it.'],
  ['JR-SDLC-003', 'sdlc-methodologies',
    'Kanban differs from Scrum principally because it:',
    ['Uses a continuous flow with WIP limits rather than fixed iterations', 'Forbids daily meetings', 'Has no board', 'Requires no estimation ever'], 0,
    'Kanban optimises flow and limits work in progress; Scrum timeboxes work into sprints. Both use boards and both can estimate.'],
  ['JR-SDLC-004', 'sdlc-methodologies',
    'The main testing drawback of a pure Waterfall model is that:',
    ['Testing starts late, so defects are found when they are most expensive', 'Testing is impossible', 'There is no documentation to test against', 'Requirements are never written'], 0,
    'Waterfall front-loads specification and back-loads verification, which is exactly the wrong shape for defect economics.'],
  ['JR-SDLC-005', 'sdlc-methodologies',
    'What does "shift right" mean in a testing context?',
    ['Extending quality activities into production: monitoring, canaries, real-user feedback', 'Moving all testing to the end of the project', 'Handing testing to developers', 'Delaying the release'], 0,
    'Shift right complements shift left: some failures only appear under real traffic, real data and real infrastructure.'],
  ['JR-SDLC-006', 'sdlc-methodologies',
    'In Scrum, who is responsible for the quality of the increment?',
    ['The whole development team', 'Only the testers', 'Only the Scrum Master', 'Only the Product Owner'], 0,
    'Scrum defines a single, cross-functional Developers accountability. A team that treats quality as "the tester job" has recreated a hand-off gate inside the sprint.'],

  // --- testing-principles -------------------------------------------------
  ['JR-PRIN-001', 'testing-principles',
    'The "pesticide paradox" states that:',
    ['Repeating the same tests eventually stops finding new defects', 'Defects cluster in a few modules', 'Testing cannot prove the absence of defects', 'Early testing saves money'], 0,
    'Test suites lose yield over time and must be reviewed and extended. It is the principle that justifies rotating and refreshing regression suites.'],
  ['JR-PRIN-002', 'testing-principles',
    'The defect clustering principle implies which practical action?',
    ['Focus extra effort on the modules that historically produce the most defects', 'Test every module equally', 'Stop testing modules with defects', 'Automate everything'], 0,
    'Defects are not uniformly distributed. Clustering is the empirical basis for risk-based test prioritisation.'],
  ['JR-PRIN-003', 'testing-principles',
    'Which statement matches the "absence-of-errors fallacy"?',
    ['A system can be defect-free and still fail to meet user needs', 'Finding no defects means the software is perfect', 'All defects can be found', 'Testing early is unnecessary'], 0,
    'Fixing everything found is not the same as building something useful. This principle is the bridge from verification to validation.'],
  ['JR-PRIN-004', 'testing-principles',
    'Why is exhaustive testing impossible for realistic systems?',
    ['The number of input and precondition combinations is effectively unbounded', 'Because tools are too slow', 'Because budgets are always cut', 'Because requirements are never complete'], 0,
    'Even a handful of fields with ordinary ranges produces a combination space no team could ever execute. This is why risk and technique-driven selection exist.'],
  ['JR-PRIN-005', 'testing-principles',
    'The principle "testing is context dependent" means:',
    ['A medical device and a marketing site require different testing approaches', 'Every project must use the same process', 'Context only matters for automation', 'Only the customer decides the approach'], 0,
    'Risk profile, regulation, lifecycle and technology all change what good testing looks like. A single fixed process applied everywhere is a smell.'],

  // --- defect-management-systems ------------------------------------------
  ['JR-DMS-001', 'defect-management-systems',
    'The primary purpose of a defect management system is to:',
    ['Track each defect from discovery to closure with a full history', 'Measure tester productivity', 'Replace direct communication', 'Store test cases'], 0,
    'The tracker is the single source of truth for defect state. Using it as a productivity scoreboard reliably corrupts the data it holds.'],
  ['JR-DMS-002', 'defect-management-systems',
    'In Jira, what is the difference between a workflow and an issue type?',
    ['The issue type says what it is; the workflow says which statuses it can move through', 'They are the same thing', 'Workflows apply only to bugs', 'Issue types define permissions'], 0,
    'A project can have several issue types sharing a workflow, or one issue type with a specialised workflow. Confusing the two makes tracker configuration debates go in circles.'],
  ['JR-DMS-003', 'defect-management-systems',
    'Why should a defect be linked to the requirement or story it violates?',
    ['It makes impact analysis and coverage reporting possible', 'It is required by Jira', 'It speeds up the fix', 'It changes the severity'], 0,
    'Links turn a pile of tickets into a queryable model of product risk.'],
  ['JR-DMS-004', 'defect-management-systems',
    'Which metric taken from the tracker is most misleading when used alone?',
    ['Number of defects reported per tester', 'Defect density per module', 'Open defects by severity', 'Average time to close'], 0,
    'Counting reports per tester rewards volume over value, and encourages splitting one defect into five tickets.'],

  // --- testing-levels -----------------------------------------------------
  ['JR-LVL-001', 'testing-levels',
    'Integration testing focuses on:',
    ['The interfaces and interactions between components', 'The internal logic of a single function', 'The system as a whole against business requirements', 'The user acceptance of the product'], 0,
    'Integration testing targets the seams. Most integration defects are contract mismatches - format, order, timing, error handling - rather than logic errors.'],
  ['JR-LVL-002', 'testing-levels',
    'Which test level is normally executed by developers on their own code?',
    ['Component (unit) testing', 'System testing', 'Acceptance testing', 'Operational acceptance testing'], 0,
    'Unit tests live with the code, run in the pipeline and are maintained by the people who change the code.'],
  ['JR-LVL-003', 'testing-levels',
    'System testing verifies:',
    ['The complete, integrated system against the specified requirements', 'A single class in isolation', 'Only the database layer', 'Only performance characteristics'], 0,
    'System testing is the first level where the product is exercised end to end in a production-like environment.'],
  ['JR-LVL-004', 'testing-levels',
    'Which of these is a form of acceptance testing?',
    ['Operational acceptance testing (backup, restore, disaster recovery)', 'Component integration testing', 'Unit testing', 'Static analysis'], 0,
    'ISTQB lists user acceptance, operational acceptance, contractual/regulatory acceptance, and alpha/beta testing as forms of acceptance testing.'],
  ['JR-LVL-005', 'testing-levels',
    'A stub or a mock is typically needed at which test level?',
    ['Component and integration testing', 'Acceptance testing', 'Beta testing', 'Usability testing'], 0,
    'Test doubles substitute for collaborators that are unavailable, slow or non-deterministic - a lower-level concern by definition.'],

  // --- oop-principles -----------------------------------------------------
  ['JR-OOP-001', 'oop-principles',
    'Encapsulation means:',
    ['Internal state is hidden and accessed only through a defined interface', 'One class inherits from another', 'The same method behaves differently per type', 'Details are hidden behind an abstract concept'], 0,
    'Encapsulation is about controlled access to state. Inheritance, polymorphism and abstraction are the other three pillars.'],
  ['JR-OOP-002', 'oop-principles',
    'Polymorphism allows:',
    ['A single interface to be backed by different implementations', 'A class to have private fields', 'Code to be compiled faster', 'Objects to be serialised'], 0,
    'This is the property that lets a Page Object framework treat a WebPage and a MobilePage through one interface.'],
  ['JR-OOP-003', 'oop-principles',
    'Why does OOP knowledge matter for a manual tester moving toward automation?',
    ['Test frameworks are built from classes, inheritance and interfaces', 'It is required to write a bug report', 'It speeds up manual execution', 'It replaces test design techniques'], 0,
    'Page Objects, base test classes, fixtures and custom assertions are all straightforward OOP once the four pillars are understood.'],
  ['JR-OOP-004', 'oop-principles',
    'Inheritance in a Page Object framework is most commonly used to:',
    ['Share common page behaviour in a base page class', 'Duplicate locators across pages', 'Avoid writing assertions', 'Replace the test runner'], 0,
    'A BasePage typically carries the driver, waits and navigation helpers, and every concrete page extends it.'],

  // --- ci-systems ---------------------------------------------------------
  ['JR-CI-001', 'ci-systems',
    'The core idea of continuous integration is that:',
    ['Changes are merged and verified automatically and frequently', 'Code is deployed to production every hour', 'Testers no longer run manual tests', 'Releases happen only at the end of a project'], 0,
    'CI is about integrating often and getting fast feedback. Continuous delivery and deployment are separate, later steps.'],
  ['JR-CI-002', 'ci-systems',
    'A test suite in CI fails intermittently without any code change. The correct first response is to:',
    ['Investigate and fix the flakiness, quarantining it explicitly if needed', 'Re-run the pipeline until it is green', 'Delete the test', 'Ignore it if the failure rate is under 50%'], 0,
    'A tolerated flaky test trains the whole team to ignore red pipelines, which is far more expensive than the test itself.'],
  ['JR-CI-003', 'ci-systems',
    'Which suite belongs in the fastest CI stage, triggered on every commit?',
    ['Unit tests and a short smoke suite', 'The full regression suite', 'Manual exploratory sessions', 'Full load tests'], 0,
    'The first stage exists to fail fast. Long suites run later, on a schedule or before release.'],
  ['JR-CI-004', 'ci-systems',
    'What is an artefact in a CI pipeline?',
    ['A build output stored for later stages, such as a package or a report', 'A defect found during the build', 'A configuration error', 'A test case'], 0,
    'Artefacts are what one stage passes to the next: binaries, containers, coverage and test reports.'],

  // --- databases ----------------------------------------------------------
  ['JR-DB-001', 'databases',
    'Which SQL statement returns customers who have never placed an order?',
    ['SELECT c.* FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.id IS NULL',
     'SELECT c.* FROM customers c INNER JOIN orders o ON o.customer_id = c.id',
     'SELECT c.* FROM customers c, orders o WHERE c.id = o.customer_id',
     'SELECT c.* FROM customers c RIGHT JOIN orders o ON o.customer_id = c.id'], 0,
    'A LEFT JOIN keeps every customer; filtering for a NULL on the right-hand side isolates those with no match. The other three all require a matching order.'],
  ['JR-DB-002', 'databases',
    'What does a PRIMARY KEY guarantee?',
    ['Uniqueness and non-nullability of the column combination', 'That the column is indexed alphabetically', 'That values are sequential', 'That the column references another table'], 0,
    'A foreign key is what references another table. A primary key identifies the row uniquely and can never be NULL.'],
  ['JR-DB-003', 'databases',
    'The difference between DELETE and TRUNCATE is that:',
    ['DELETE removes rows one by one and can be filtered; TRUNCATE empties the table wholesale', 'They are identical', 'TRUNCATE can use a WHERE clause', 'DELETE removes the table structure'], 0,
    'TRUNCATE is faster but unfilterable, and in many engines it cannot be rolled back and resets identity counters. DROP is what removes the structure.'],
  ['JR-DB-004', 'databases',
    'Which is a defining characteristic of a NoSQL document store such as MongoDB?',
    ['Schema-flexible documents rather than fixed relational tables', 'Strict foreign key enforcement', 'Support for SQL joins only', 'Data must be normalised to third normal form'], 0,
    'Document stores trade rigid schema and joins for flexibility and horizontal scale, which changes what a tester must check about data consistency.'],
  ['JR-DB-005', 'databases',
    'Why should a tester be able to query the database directly?',
    ['To verify what the system actually stored, not just what the UI displays', 'To fix production data', 'To replace API testing', 'To speed up the UI'], 0,
    'The UI can display a cached or transformed value. Direct verification separates a presentation defect from a persistence defect.'],
  ['JR-DB-006', 'databases',
    'Which clause filters rows AFTER aggregation in SQL?',
    ['HAVING', 'WHERE', 'ORDER BY', 'GROUP BY'], 0,
    'WHERE filters rows before grouping; HAVING filters the aggregated groups. Using WHERE on an aggregate is a classic error.'],

  // --- web-app-architecture -----------------------------------------------
  ['JR-ARCH-001', 'web-app-architecture',
    'In a classic three-tier web application, the tiers are:',
    ['Presentation, application/business logic, and data', 'HTML, CSS and JavaScript', 'Frontend, backend and QA', 'Development, staging and production'], 0,
    'The three-tier split is the mental model that lets a tester localise a defect to a layer before writing the report.'],
  ['JR-ARCH-002', 'web-app-architecture',
    'What does a load balancer do?',
    ['Distributes incoming requests across several server instances', 'Compresses images', 'Caches database queries', 'Encrypts passwords'], 0,
    'Load balancers also affect testing: sticky sessions, or their absence, explain many "I was logged out at random" reports.'],
  ['JR-ARCH-003', 'web-app-architecture',
    'A microservice architecture makes which testing activity noticeably harder?',
    ['End-to-end testing across service boundaries', 'Unit testing', 'Static analysis', 'Code review'], 0,
    'Independent deployability multiplies the number of version combinations, which is why contract testing became popular.'],
  ['JR-ARCH-004', 'web-app-architecture',
    'A CDN in front of an application primarily affects testing because:',
    ['Cached content can mask a fresh deployment', 'It changes the database schema', 'It rewrites the business logic', 'It removes the need for HTTPS'], 0,
    'Verifying against a stale CDN copy is a routine source of false "the fix did not work" reports.'],
  ['JR-ARCH-005', 'web-app-architecture',
    'Client-side rendering (SPA) versus server-side rendering matters to a tester because:',
    ['Content may appear after the initial HTML, so waits and SEO checks differ', 'SPAs cannot be automated', 'SSR pages have no JavaScript', 'SPAs never make network calls'], 0,
    'In an SPA the DOM is assembled after load, which is the root cause of most naive-automation timing flakiness.'],

  // --- rest-http ----------------------------------------------------------
  ['JR-HTTP-001', 'rest-http',
    'Which HTTP status code family indicates a client-side error?',
    ['4xx', '2xx', '3xx', '5xx'], 0,
    '4xx means the request was wrong (bad syntax, unauthorised, not found). 5xx means the server failed while handling a valid request.'],
  ['JR-HTTP-002', 'rest-http',
    'What is the difference between 401 and 403?',
    ['401 means not authenticated; 403 means authenticated but not permitted', 'They are interchangeable', '401 is a server error', '403 means the resource does not exist'], 0,
    'Sending 401 where 403 belongs is a real, reportable API defect: it tells a client to retry authentication that would never help.'],
  ['JR-HTTP-003', 'rest-http',
    'Which HTTP method is expected to be idempotent?',
    ['PUT', 'POST', 'PATCH is always idempotent', 'None of them'], 0,
    'GET, PUT and DELETE are idempotent: repeating them leaves the same state. POST is not, and PATCH is only if written that way.'],
  ['JR-HTTP-004', 'rest-http',
    'A POST that successfully creates a resource should normally return:',
    ['201 Created with a Location header', '200 OK with an empty body', '204 No Content', '302 Found'], 0,
    '201 plus Location tells the client both that creation succeeded and where the new resource lives.'],
  ['JR-HTTP-005', 'rest-http',
    'What does the HTTP header "Content-Type: application/json" tell the server?',
    ['The request body is JSON and should be parsed as such', 'The response must be JSON', 'The connection is encrypted', 'The request is cacheable'], 0,
    'Accept is the header that states what the client wants back; Content-Type describes what is being sent.'],
  ['JR-HTTP-006', 'rest-http',
    'HTTPS differs from HTTP because it:',
    ['Encrypts the traffic with TLS and authenticates the server certificate', 'Is faster', 'Uses a different HTML dialect', 'Does not use cookies'], 0,
    'HTTPS provides confidentiality, integrity and server authentication. Testing it includes certificate validity, chain and mixed-content checks.'],
  ['JR-HTTP-007', 'rest-http',
    'Which status code is correct when a request is well-formed but fails business validation?',
    ['422 Unprocessable Content (or 400 Bad Request)', '500 Internal Server Error', '404 Not Found', '204 No Content'], 0,
    'Returning 500 for a validation failure hides a client mistake behind a server-fault code and pollutes error monitoring.'],

  // --- story-verification -------------------------------------------------
  ['JR-STORY-001', 'story-verification',
    'A story has five acceptance criteria. Four pass, one fails. The story should be:',
    ['Returned to development as not done', 'Accepted with a follow-up ticket', 'Accepted because 80% passed', 'Accepted if the failing criterion is cosmetic'], 0,
    'Acceptance criteria are a conjunction, not a score. Partial acceptance quietly redefines done for the whole team.'],
  ['JR-STORY-002', 'story-verification',
    'While verifying a story you find behaviour that is not covered by any acceptance criterion. You should:',
    ['Raise the gap with the product owner before deciding whether it is a defect', 'Report it as a defect immediately', 'Ignore it', 'Change the acceptance criteria yourself'], 0,
    'An uncovered behaviour is first a requirements gap. Whether it becomes a defect depends on the intent, which the product owner holds.'],
  ['JR-STORY-003', 'story-verification',
    'Verifying "in strict accordance with acceptance criteria" means the tester:',
    ['Checks every criterion explicitly and records the result per criterion', 'Tests whatever seems risky', 'Runs only the regression suite', 'Relies on the developer demo'], 0,
    'Per-criterion evidence is what makes acceptance auditable and what stops "we thought that was covered" at release time.'],
  ['JR-STORY-004', 'story-verification',
    'The most appropriate moment to review acceptance criteria for testability is:',
    ['During refinement, before the story enters a sprint', 'During the sprint review', 'After the story is coded', 'At release'], 0,
    'Reviewing criteria at refinement is the cheapest defect prevention available to a tester.'],

  // --- rough-estimation ---------------------------------------------------
  ['JR-EST-001', 'rough-estimation',
    'A rough estimate for testing a small story should account for:',
    ['Analysis, design, execution, defect reporting and retesting', 'Execution time only', 'Only the time to write test cases', 'Only the time to report defects'], 0,
    'Estimates that count only execution are consistently 2-3x low, because reporting and retesting are where the tail actually lives.'],
  ['JR-EST-002', 'rough-estimation',
    'You are asked for an estimate on a story whose requirements are still unclear. The professional answer is:',
    ['Give a range with stated assumptions, or ask for a timeboxed spike first', 'Give a single confident number', 'Refuse to estimate', 'Copy the estimate of a similar story'], 0,
    'A range communicates uncertainty honestly. A single number invented from an unclear requirement becomes a commitment you did not intend to make.'],
  ['JR-EST-003', 'rough-estimation',
    'Why should retesting and regression be included in a testing estimate?',
    ['Defects will be found, fixed and must be verified, and neighbours must be rechecked', 'To inflate the estimate', 'Because the customer asks for it', 'Only for large projects'], 0,
    'Every defect found generates verification work later. An estimate assuming zero defects is an estimate assuming the testing was unnecessary.'],
  ['JR-EST-004', 'rough-estimation',
    'Your estimate is exceeded halfway through the task. You should:',
    ['Flag it immediately with the current status and a revised estimate', 'Work overtime silently', 'Reduce test coverage without telling anyone', 'Wait until the deadline to report it'], 0,
    'Overruns are only a problem when they are a surprise. Early escalation preserves everyone options.'],

  // --- requirements-testing -----------------------------------------------
  ['JR-REQ-001', 'requirements-testing',
    'Which requirement defect is present in "The system must be user-friendly"?',
    ['It is not verifiable', 'It is not consistent', 'It is not complete', 'It is not traceable'], 0,
    'There is no test that can produce a pass or a fail. Verifiability is the property a tester should check first.'],
  ['JR-REQ-002', 'requirements-testing',
    'Two requirements state different maximum file sizes for the same upload. This is a defect of:',
    ['Consistency', 'Verifiability', 'Traceability', 'Feasibility'], 0,
    'Contradictory requirements guarantee that one of them will be implemented and the other reported as a bug later.'],
  ['JR-REQ-003', 'requirements-testing',
    'Reviewing requirements before code exists is valuable mainly because:',
    ['A defect removed there costs a fraction of the same defect in production', 'It fills tester time before the build arrives', 'It is required by ISO', 'It replaces system testing'], 0,
    'Static testing of requirements is the highest-leverage activity available to a tester, and it needs no environment.'],
  ['JR-REQ-004', 'requirements-testing',
    'A requirement says "the report must load quickly for all users". The best tester response is:',
    ['Ask for a measurable target: which percentile, which data volume, which network', 'Accept it and test subjectively', 'Reject the requirement outright', 'Write a test case that says "loads quickly"'], 0,
    'Turning a vague quality statement into a measurable one is requirements testing in its most practical form.'],

  // --- test-planning-tasks ------------------------------------------------
  ['JR-PLAN-001', 'test-planning-tasks',
    'When planning testing for a specific task, the first thing to establish is:',
    ['What the change affects and what risk it carries', 'How many test cases to write', 'Which tool to use', 'Who will execute the tests'], 0,
    'Scope and risk determine everything downstream. Deciding the count or the tool first is planning backwards.'],
  ['JR-PLAN-002', 'test-planning-tasks',
    'You have two days to test a feature that would need five to cover fully. The right approach is to:',
    ['Prioritise by risk, state explicitly what will not be covered, and agree it', 'Test everything superficially', 'Test the first half thoroughly and stop', 'Silently extend the deadline'], 0,
    'The deliverable of a constrained plan is an explicit, agreed coverage gap - not an implicit one nobody knows about.'],
  ['JR-PLAN-003', 'test-planning-tasks',
    'Which of these is an entry criterion for starting test execution on a task?',
    ['The build is deployed to the test environment and smoke checks pass', 'All defects are closed', 'The test report is written', 'The customer has signed off'], 0,
    'Entry criteria gate the start of execution; exit criteria gate its end. The other three options are exit-side concerns.'],
  ['JR-PLAN-004', 'test-planning-tasks',
    'Test data preparation should be planned:',
    ['Together with test design, before execution starts', 'During execution as it is needed', 'After execution', 'Only for automated tests'], 0,
    'Data is one of the most common causes of blocked execution. Planning it late converts design time into idle time.'],

  // --- english-writing ----------------------------------------------------
  ['JR-ENGW-001', 'english-writing',
    'Which is the most appropriate opening for an email to a customer reporting a release risk?',
    ['We found an issue in the payment flow that may affect Friday release. Details and options below.',
     'Hi! Bad news again...',
     'The developers broke payments once more.',
     'FYI, there might be something wrong somewhere.'], 0,
    'State the subject, the impact and the fact that options follow. Blame and vagueness both cost the reader time and cost you credibility.'],
  ['JR-ENGW-002', 'english-writing',
    'In written test documentation, the preferred style for steps is:',
    ['Short imperative sentences: "Open the cart", "Enter 5 in Quantity"',
     'Long descriptive paragraphs',
     'Past tense narration',
     'Questions to the reader'], 0,
    'Imperative steps are unambiguous, scannable and translate directly into automation.'],
  ['JR-ENGW-003', 'english-writing',
    'When you do not yet know the cause of a defect, the honest phrasing in a customer-facing update is:',
    ['We are investigating and will confirm the root cause by end of day',
     'It is a back-end problem',
     'Nothing serious, it will fix itself',
     'The developers are looking into their mistake'], 0,
    'Commit to a time for the next update rather than to a cause you have not established.'],
  ['JR-ENGW-004', 'english-writing',
    'Which sentence is clearest in a test summary?',
    ['3 of 45 regression cases failed; all three relate to the discount calculation',
     'There were some failures in regression',
     'Regression was mostly fine',
     'Almost everything passed'], 0,
    'Numbers plus a stated pattern let the reader act. Hedged summaries force them to ask a follow-up question.'],
]);
