import { defineQuestions } from '../define.js';

/**
 * ISTQB Certified Tester Foundation Level (CTFL v4.0).
 *
 * Placed at the Junior tier because the Performance Review sheet names
 * "Foundations Level - ISTQB" as an expectation of the Junior rung.
 * Chapter weighting follows the exam blueprint, which puts the most weight on
 * chapter 4 (test analysis and design) and chapter 5 (managing test activities).
 */
export const juniorCtflQuestions = defineQuestions('junior', 'istqb-ctfl', [
  // --- Ch.1 Fundamentals of testing ---------------------------------------
  ['FL-1-001', 'testing-phases-goals',
    'Which of the following is a typical objective of testing?',
    ['Building confidence in the level of quality of the test object', 'Removing all defects from the code', 'Proving that the software is correct', 'Guaranteeing zero production incidents'], 0,
    'CTFL lists evaluating work products, causing failures, ensuring coverage, reducing risk, complying with requirements and building confidence among the objectives. Proof of correctness is not among them.'],
  ['FL-1-002', 'testing-principles',
    'A tester finds no defects in a component. What can be concluded?',
    ['Nothing about the absence of defects in that component', 'The component is defect-free', 'The tests were badly designed', 'The component is ready for production'], 0,
    'Principle 2: testing shows the presence of defects, never their absence. The result is one piece of information, not a verdict on quality.'],
  ['FL-1-003', 'defect-lifecycle',
    'A developer types the wrong comparison operator; the program then computes a wrong total; the user sees an incorrect invoice. Match the terms.',
    ['Error -> defect -> failure', 'Failure -> defect -> error', 'Defect -> error -> failure', 'Error -> failure -> defect'], 0,
    'A human error introduces a defect in the code, and executing that defect may cause a failure that the user observes. Not every defect produces a failure.'],
  ['FL-1-004', 'testing-phases-goals',
    'Which activity is part of test analysis rather than test design?',
    ['Deciding WHAT to test by evaluating the test basis', 'Deciding HOW to test by producing test cases', 'Creating test data and test procedures', 'Executing the test suite'], 0,
    'Analysis identifies testable features and defines test conditions. Design turns those conditions into test cases; implementation creates the concrete data and procedures.'],
  ['FL-1-005', 'testing-principles',
    'Which principle explains why regression suites must be reviewed and updated?',
    ['Tests wear out', 'Defects cluster together', 'Testing is context dependent', 'Early testing saves time and money'], 0,
    'The pesticide paradox: unchanged tests stop finding new defects, so the suite must be revised and extended over time.'],
  ['FL-1-006', 'testing-types',
    'What distinguishes testing from debugging?',
    ['Testing finds failures; debugging locates and removes their causes', 'They are synonyms', 'Testing is done by developers, debugging by testers', 'Debugging happens before testing'], 0,
    'CTFL v4 is explicit that they are different activities with different owners, even though a confirmation test follows a debug.'],
  ['FL-1-007', 'test-documentation',
    'Traceability from test cases back to the test basis primarily supports:',
    ['Coverage assessment and impact analysis when the basis changes', 'Faster test execution', 'Reduced test maintenance cost', 'Higher defect detection rate'], 0,
    'Traceability answers "what is covered" and "what must be retested", and it is what makes test progress reporting meaningful.'],

  // --- Ch.2 Testing throughout the SDLC -----------------------------------
  ['FL-2-001', 'sdlc-methodologies',
    'Which is a good testing practice in ANY software development lifecycle model?',
    ['Every development activity has a corresponding test activity', 'All testing happens after coding is complete', 'Only the test team performs testing', 'Test levels never overlap'], 0,
    'CTFL states that in every model each development activity should have a corresponding test activity, and testers should be involved in reviewing work products as soon as drafts exist.'],
  ['FL-2-002', 'testing-levels',
    'Which test level is MOST focused on interfaces and interactions between integrated components?',
    ['Component integration testing', 'Component testing', 'System testing', 'Acceptance testing'], 0,
    'Component integration testing targets the interfaces between components. System integration testing targets interfaces to other systems and external services.'],
  ['FL-2-003', 'testing-types',
    'Confirmation testing is performed to:',
    ['Verify that a previously failing defect has actually been fixed', 'Check that unchanged areas still work', 'Measure system performance', 'Validate the requirements'], 0,
    'Confirmation testing (retesting) is about the fix. Regression testing is about the collateral damage the fix may have caused.'],
  ['FL-2-004', 'testing-types',
    'Which testing type verifies that a change has not adversely affected unchanged parts of the system?',
    ['Regression testing', 'Confirmation testing', 'Maintenance testing', 'Smoke testing'], 0,
    'Maintenance testing is the context (a change to a deployed system); regression testing is the technique used inside it.'],
  ['FL-2-005', 'sdlc-methodologies',
    'Shift-left testing means:',
    ['Performing testing activities earlier in the lifecycle', 'Moving the test team to another project', 'Automating everything', 'Testing only in production'], 0,
    'Shift left includes reviewing requirements, writing tests before code, and running static analysis in CI.'],
  ['FL-2-006', 'testing-levels',
    'Which is an example of operational acceptance testing?',
    ['Verifying backup and restore procedures', 'Verifying a business workflow with end users', 'Verifying compliance with a contract', 'Verifying a single function in isolation'], 0,
    'Operational acceptance testing covers the operational aspects: backup/restore, disaster recovery, user management, maintenance tasks and security checks.'],

  // --- Ch.3 Static testing ------------------------------------------------
  ['FL-3-001', 'requirements-testing',
    'Which is a benefit of static testing that dynamic testing cannot offer?',
    ['Defects can be found before any code is executable', 'Failures are observed under real load', 'Response times are measured', 'Memory leaks are detected'], 0,
    'Static testing examines work products without executing them, which is why it can start on a requirements draft.'],
  ['FL-3-002', 'requirements-testing',
    'Which review type is the MOST formal, with defined roles, entry criteria and metrics?',
    ['Inspection', 'Walkthrough', 'Informal review', 'Technical review'], 0,
    'CTFL orders reviews by formality: informal review, walkthrough, technical review, inspection.'],
  ['FL-3-003', 'requirements-testing',
    'In a formal review, who leads the meeting and mediates between participants?',
    ['The moderator (facilitator)', 'The author', 'The scribe', 'The manager'], 0,
    'The author must not moderate their own review; the moderator keeps it about the work product rather than the person.'],
  ['FL-3-004', 'static-analysis',
    'Static analysis tools typically detect:',
    ['Coding standard violations, unreachable code and suspicious constructs', 'Slow database queries under load', 'Usability problems', 'Incorrect business rules'], 0,
    'Static analysis works on the code structure. Business-rule correctness needs an oracle the tool does not have.'],
  ['FL-3-005', 'requirements-testing',
    'The MOST important success factor for a review is that:',
    ['Objectives are clear and participants are prepared', 'The meeting is short', 'The author defends the work product', 'Managers attend'], 0,
    'Unprepared participants turn a review into a reading session, which finds the defects a proof-reader would find and no others.'],

  // --- Ch.4 Test analysis and design (heaviest chapter) -------------------
  ['FL-4-001', 'test-design-techniques',
    'Which is a black-box test technique?',
    ['Equivalence partitioning', 'Statement testing', 'Branch testing', 'Decision testing'], 0,
    'Statement, branch and decision testing are white-box: they need the code structure. Equivalence partitioning works from the specification.'],
  ['FL-4-002', 'test-design-techniques',
    'A system accepts amounts from 100 to 999. Using three-value boundary value analysis on the lower boundary, the values are:',
    ['99, 100, 101', '100, 101, 102', '98, 99, 100', '99, 100, 999'], 0,
    'The three-value approach takes the boundary and its neighbours on both sides.'],
  ['FL-4-003', 'test-design-techniques',
    'Which coverage is achieved when every statement in the code has been executed at least once?',
    ['Statement coverage', 'Branch coverage', 'Decision coverage', 'Path coverage'], 0,
    '100% branch coverage implies 100% statement coverage, but not the other way around: a lone if with no else reaches every statement without taking the false branch.'],
  ['FL-4-004', 'test-design-techniques',
    'A decision table has 3 conditions, each true or false. How many rules does the full (non-collapsed) table have?',
    ['8', '6', '9', '3'], 0,
    '2^3 = 8. The table can then be collapsed by merging rules where a condition does not affect the outcome.'],
  ['FL-4-005', 'test-design-techniques',
    'Which technique is BEST for testing an order that moves through Created, Paid, Shipped and Delivered?',
    ['State transition testing', 'Equivalence partitioning', 'Decision table testing', 'Statement testing'], 0,
    'The behaviour depends on the current state and the event, which is exactly what a state transition model captures - including the invalid transitions worth testing.'],
  ['FL-4-006', 'test-design-techniques',
    'Which is an experience-based test technique?',
    ['Exploratory testing', 'Boundary value analysis', 'Decision table testing', 'Branch testing'], 0,
    'CTFL v4 lists error guessing, exploratory testing and checklist-based testing as the experience-based techniques.'],
  ['FL-4-007', 'test-design-techniques',
    'What is the main purpose of a coverage criterion?',
    ['To provide an objective measure of the thoroughness of a test suite', 'To guarantee defect-free code', 'To replace test design', 'To estimate test effort'], 0,
    'Coverage is a measure of what was exercised, not of quality: 100% statement coverage with weak assertions can find nothing.'],
  ['FL-4-008', 'test-design-techniques',
    'A field accepts a 3-letter country code. Which is an INVALID equivalence partition?',
    ['A 4-character input', 'The value USA', 'The value GBR', 'The value POL'], 0,
    'Length is the partitioning attribute here: anything other than exactly three letters falls into an invalid partition.'],
  ['FL-4-009', 'test-design-techniques',
    'Collaboration-based test approaches such as ATDD produce:',
    ['Test cases derived collaboratively from user stories and acceptance criteria', 'Only automated unit tests', 'Only performance tests', 'Only exploratory charters'], 0,
    'Acceptance test-driven development turns the three-amigos conversation into concrete acceptance tests before the code is written.'],
  ['FL-4-010', 'test-design-techniques',
    'Given a login that locks after 3 failed attempts, which test design technique most directly derives the test cases?',
    ['State transition testing', 'Boundary value analysis alone', 'Statement testing', 'Checklist-based testing'], 0,
    'Attempt count is state. The interesting cases are the transitions at 1, 2, 3 failures and the reset on a successful login.'],
  ['FL-4-011', 'test-design-techniques',
    'Branch coverage of 100% guarantees:',
    ['100% statement coverage', '100% path coverage', 'No defects remain', 'All requirements are covered'], 0,
    'Branch coverage subsumes statement coverage. Path coverage is strictly stronger than both and is usually infeasible.'],
  ['FL-4-012', 'test-design-techniques',
    'Which of the following is NOT a valid reason to use white-box techniques?',
    ['They validate that the software meets user needs', 'They reveal untested code', 'They provide objective coverage measures', 'They can be automated in the pipeline'], 0,
    'Structure-based techniques say nothing about whether the implemented behaviour is the behaviour the user wanted.'],

  // --- Ch.5 Managing the test activities ----------------------------------
  ['FL-5-001', 'risks-in-testing',
    'Risk level is determined by:',
    ['The likelihood of the risk occurring and the impact if it does', 'The number of defects found so far', 'The size of the test team', 'The number of requirements'], 0,
    'Risk = likelihood x impact. Both dimensions must be assessed, since a catastrophic but impossible event and a certain but trivial one need different responses.'],
  ['FL-5-002', 'risks-in-testing',
    'A product risk is:',
    ['A risk that the product may fail to satisfy a stakeholder need', 'A risk that the project will be late', 'A risk that a supplier withdraws', 'A risk that the team lacks skills'], 0,
    'Project risks (schedule, staffing, suppliers) threaten the ability to deliver; product risks threaten the quality of what is delivered.'],
  ['FL-5-003', 'test-plan',
    'Which is typically included in a test plan?',
    ['Scope, objectives, risks, entry and exit criteria, and the test approach', 'The full list of executed test cases with results', 'The source code of the automation framework', 'The defect reports of the previous release'], 0,
    'A plan is forward-looking. Results belong in the test progress and completion reports.'],
  ['FL-5-004', 'testing-metrics',
    'Exit criteria (definition of done for a test level) exist to:',
    ['Define objectively when enough testing has been done', 'Set the start date of testing', 'Determine who executes the tests', 'Prioritise defects'], 0,
    'Without agreed exit criteria, "are we done testing?" becomes a negotiation under deadline pressure rather than a check against a rule.'],
  ['FL-5-005', 'testing-metrics',
    'Which metric best supports a release decision?',
    ['Residual risk expressed through coverage of high-risk areas and open defects by severity', 'Total number of test cases written', 'Number of hours spent testing', 'Number of testers on the team'], 0,
    'A release decision is a risk decision. Effort and volume metrics describe the test team, not the product.'],
  ['FL-5-006', 'risks-in-testing',
    'In risk-based testing, high-risk areas should be:',
    ['Tested earlier and more deeply', 'Tested last, when the build is stable', 'Tested only if time permits', 'Excluded to save effort'], 0,
    'Testing early on the highest risks maximises the information gained per unit of time, and leaves room to react.'],
  ['FL-5-007', 'defect-lifecycle',
    'Which information is essential in a defect report to allow prioritisation?',
    ['Severity, impact on the business and steps to reproduce', 'The tester name and mood', 'The number of test cases affected only', 'The exact time of day'], 0,
    'CTFL lists identification, description, severity, priority, status, references and evidence among the expected contents.'],
  ['FL-5-008', 'test-plan',
    'A test approach describes:',
    ['How testing will be implemented for a particular product or project', 'The exact steps of every test case', 'The defect workflow in the tracker', 'The build pipeline configuration'], 0,
    'The approach tailors the strategy to the context: which levels, which techniques, which automation, which entry and exit criteria.'],
  ['FL-5-009', 'testing-metrics',
    'Test progress reporting should communicate primarily:',
    ['Status against the plan, product risks and impediments', 'How many hours each tester logged', 'The number of defects each developer created', 'The volume of documentation produced'], 0,
    'The purpose of a progress report is to support a decision by the stakeholders reading it.'],

  // --- Ch.6 Test tools ----------------------------------------------------
  ['FL-6-001', 'auto-web-ui',
    'A common risk when introducing test automation is:',
    ['Unrealistic expectations about the effort and benefits', 'Tests running too fast', 'Too much coverage', 'Reduced defect counts'], 0,
    'CTFL is explicit that automation costs are underestimated: maintenance, environment and skills dominate the total cost, not the initial scripting.'],
  ['FL-6-002', 'auto-web-ui',
    'Which is the strongest candidate for automation?',
    ['A stable, frequently repeated regression check', 'A one-off exploratory session', 'A usability evaluation with real users', 'A test whose expected result changes weekly'], 0,
    'Automation pays back through repetition against a stable oracle. Volatile or judgement-based checks pay negative interest.'],
  ['FL-6-003', 'auto-web-ui',
    'A pilot project before rolling out a new test tool is recommended in order to:',
    ['Evaluate fit with the existing process and technology at low cost', 'Delay the decision', 'Train the whole company at once', 'Satisfy the vendor'], 0,
    'A pilot converts a purchasing argument into evidence about your own codebase and your own team.'],
]);
