import { defineQuestions } from '../define.js';

/**
 * ISTQB Advanced Level - Test Analyst (CTAL-TA), asked at the Middle tier.
 *
 * The Performance Review sheet expects ISTQB Advanced Level at the Senior rung
 * and treats analytical work (requirements testing, test design, process
 * analysis) as a Middle-tier competency, so Test Analyst material is split:
 * the design- and analysis-heavy topics sit here, the harder judgement calls
 * sit in the senior file.
 */
export const middleCtalTaQuestions = defineQuestions('middle', 'istqb-ctal-ta', [
  // --- Test process for the Test Analyst ----------------------------------
  ['TA-P-001', 'requirements-testing',
    'During test analysis, the Test Analyst identifies test conditions. The best source when requirements are incomplete is:',
    ['A combination of stakeholders, existing systems and experience-based techniques', 'Guessing what the developer implemented', 'The defect tracker only', 'The previous project test cases'], 0,
    'CTAL-TA expects the analyst to work with an imperfect test basis by combining available sources rather than waiting for perfect requirements.'],
  ['TA-P-002', 'test-planning-tasks',
    'Which factor most influences the level of detail in test conditions?',
    ['The level of risk and the intended reuse of the tests', 'The number of testers', 'The tool licence', 'The sprint length'], 0,
    'High-risk, reusable and audited tests justify detail. Low-risk one-off exploration does not.'],
  ['TA-P-003', 'test-documentation',
    'Low-level (concrete) test cases are preferred over high-level (logical) ones when:',
    ['The testers are less experienced or the results must be auditable and repeatable', 'The requirements change every day', 'Time is very short', 'The system is exploratory in nature'], 0,
    'Concrete cases cost more to maintain but survive being executed by someone who does not know the system.'],
  ['TA-P-004', 'process-analysis',
    'A Test Analyst notices that the test basis is untestable in several places. The correct action is:',
    ['Raise the issues as defects in the test basis before test design starts', 'Design tests anyway and interpret freely', 'Wait for the code and test against it', 'Escalate to the customer directly'], 0,
    'Reporting test-basis defects is one of the highest-value activities the analyst performs, and it must happen before design effort is spent.'],

  // --- Risk-based testing for the Test Analyst ----------------------------
  ['TA-R-001', 'risks-in-testing',
    'In risk-based testing, the Test Analyst usually contributes primarily to:',
    ['Identifying and assessing product risks from the business and user perspective', 'Setting the project budget', 'Assigning developers to modules', 'Choosing the CI server'], 0,
    'The Test Manager owns the process; the Test Analyst supplies the domain judgement about likelihood and impact.'],
  ['TA-R-002', 'risks-in-testing',
    'A risk-mitigation activity for a high-impact, low-likelihood risk is best described as:',
    ['Targeted deep testing of that specific area, even though it is rare', 'Ignoring it because it is unlikely', 'Uniform coverage across all areas', 'Deferring it to production monitoring only'], 0,
    'Impact dominates when the consequence is unacceptable, which is why rare catastrophic paths still get dedicated tests.'],
  ['TA-R-003', 'risks-in-testing',
    'Risk levels should be reassessed:',
    ['Throughout the project as new information arrives', 'Once, at the start', 'Only after a production incident', 'Only when the customer asks'], 0,
    'A risk register written once and never revisited becomes a historical document rather than a planning tool.'],

  // --- Test techniques ----------------------------------------------------
  ['TA-T-001', 'test-design-techniques',
    'Classification tree analysis is most closely related to which other technique?',
    ['Equivalence partitioning combined with combinatorial testing', 'Statement coverage', 'State transition testing', 'Error guessing'], 0,
    'The tree structures the input space into classes, and the combination table then selects the combinations to execute.'],
  ['TA-T-002', 'test-design-techniques',
    'Pairwise testing is justified by the empirical observation that:',
    ['Most combinatorial defects are triggered by interactions of only two parameters', 'All defects are single-parameter', 'Exhaustive combinations are cheap', 'Parameters never interact'], 0,
    'Pairwise gives a large reduction in test count for a small loss of theoretical coverage - the classic risk-informed trade.'],
  ['TA-T-003', 'test-design-techniques',
    'Domain analysis extends boundary value analysis and equivalence partitioning by:',
    ['Considering combinations of interacting variables using on/off/in/out points', 'Removing the need for boundaries', 'Only testing invalid values', 'Working only on single variables'], 0,
    'Domain analysis is the technique to reach for when two or more numeric fields constrain each other.'],
  ['TA-T-004', 'test-design-techniques',
    'A use case test is derived from:',
    ['The basic flow plus the alternative and exception flows', 'The database schema', 'The source code branches', 'The defect history only'], 0,
    'Use case testing is strong at finding integration and workflow defects because it follows how the system is actually used.'],
  ['TA-T-005', 'test-design-techniques',
    'A state transition table is particularly good at exposing:',
    ['Invalid transitions that the specification never mentioned', 'Performance bottlenecks', 'Memory leaks', 'Coding standard violations'], 0,
    'The table forces every state/event pair to be considered, including the ones the specification silently ignored.'],
  ['TA-T-006', 'test-design-techniques',
    'Defect-based test design techniques use:',
    ['A defect taxonomy to derive tests targeting known defect types', 'The code structure', 'The state model', 'The performance profile'], 0,
    'A taxonomy built from your own escaped-defect history is one of the most productive test design inputs available.'],
  ['TA-T-007', 'test-design-techniques',
    'Checklist-based testing is an experience-based technique whose main weakness is:',
    ['Coverage varies with the tester, and checklists go stale', 'It cannot be documented', 'It is too slow', 'It requires source code'], 0,
    'Checklists must be maintained from real findings, otherwise they encode the risks of three years ago.'],
  ['TA-T-008', 'test-design-techniques',
    'In session-based test management, a charter defines:',
    ['The mission and scope of a timeboxed exploratory session', 'The exact steps to execute', 'The expected results in advance', 'The defect severity scale'], 0,
    'The charter makes exploratory testing plannable and reportable without turning it into scripted testing.'],
  ['TA-T-009', 'test-design-techniques',
    'A system has 4 boolean configuration flags and 3 user roles. Full combinatorial coverage requires 48 cases. Pairwise would need roughly:',
    ['Fewer than 15', 'Exactly 48', 'Exactly 24', 'More than 48'], 0,
    'Pairwise typically collapses such spaces by an order of magnitude while covering every pair of values at least once.'],
  ['TA-T-010', 'test-design-techniques',
    'When should a Test Analyst combine several techniques on the same feature?',
    ['When the feature has both complex business rules and stateful behaviour', 'Never - one technique per feature', 'Only when time allows', 'Only for automated tests'], 0,
    'Decision tables cover the rules, state transition covers the history, and boundary analysis covers the numeric edges. They are complementary, not alternatives.'],

  // --- Testing quality characteristics ------------------------------------
  ['TA-Q-001', 'testing-types',
    'Functional appropriateness, as a quality sub-characteristic, is about:',
    ['Whether the functions facilitate the accomplishment of the user tasks', 'Whether the function returns the right value', 'Whether all specified functions are present', 'Whether the system is fast'], 0,
    'ISO 25010 splits functional suitability into completeness (all present), correctness (right results) and appropriateness (actually helps the task).'],
  ['TA-Q-002', 'testing-types',
    'Usability testing that measures whether a user can complete a task at all is evaluating:',
    ['Effectiveness', 'Efficiency', 'Satisfaction', 'Learnability'], 0,
    'Effectiveness = can they finish; efficiency = at what cost in time and effort; satisfaction = how it felt.'],
  ['TA-Q-003', 'testing-types',
    'Which is a portability sub-characteristic relevant to a Test Analyst?',
    ['Installability', 'Maturity', 'Time behaviour', 'Confidentiality'], 0,
    'Portability covers adaptability, installability and replaceability. Maturity is reliability, time behaviour is performance efficiency, confidentiality is security.'],
  ['TA-Q-004', 'testing-types',
    'Compatibility testing in ISO 25010 covers:',
    ['Co-existence with other software and interoperability with other systems', 'Response time under load', 'Fault tolerance', 'Code readability'], 0,
    'Co-existence defects (two apps fighting over a port or a driver) are routinely missed because each product is tested alone.'],
  ['TA-Q-005', 'testing-types',
    'Accessibility testing should verify, at minimum:',
    ['Keyboard operability, text alternatives and sufficient contrast', 'Only screen reader support', 'Only colour contrast', 'Only font size'], 0,
    'WCAG covers perceivable, operable, understandable and robust. Testing only one of the four leaves the majority of barriers in place.'],
  ['TA-Q-006', 'testing-types',
    'Which usability defect would a heuristic evaluation find that a scripted functional test would not?',
    ['The user has no way to recognise which step of the process they are on', 'A button returns a 500 error', 'A field accepts 300 characters instead of 200', 'A total is calculated incorrectly'], 0,
    'Heuristic evaluation targets exactly the class of problems where nothing is technically broken but the user is lost.'],

  // --- Reviews ------------------------------------------------------------
  ['TA-V-001', 'requirements-testing',
    'When reviewing requirements, the Test Analyst is best placed to check:',
    ['Testability, completeness and consistency from a user perspective', 'Compiler warnings', 'Database indexes', 'Deployment scripts'], 0,
    'The analyst brings the question "how would I prove this?" which is precisely the question that exposes untestable requirements.'],
  ['TA-V-002', 'requirements-testing',
    'A review checklist for user stories should include:',
    ['Independent, negotiable, valuable, estimable, small, testable (INVEST)', 'Number of words', 'Author seniority', 'Story point value'], 0,
    'INVEST is a widely used checklist; the "testable" criterion is the one a Test Analyst must defend hardest.'],
  ['TA-V-003', 'requirements-testing',
    'The main benefit of the Test Analyst participating in reviews early is:',
    ['Defects are prevented rather than detected later', 'It fills time before the build', 'It reduces documentation', 'It replaces test design'], 0,
    'Prevention is orders of magnitude cheaper than detection, and it is the highest-leverage use of an analyst time.'],

  // --- Defect management --------------------------------------------------
  ['TA-D-001', 'defect-management-systems',
    'A defect taxonomy is used to:',
    ['Categorise defects so patterns and process weaknesses become visible', 'Assign blame', 'Speed up fixes', 'Replace severity'], 0,
    'Once defects are classified, the same category appearing repeatedly points at a missing gate in the process.'],
  ['TA-D-002', 'defect-management-systems',
    'A false positive in testing is:',
    ['A reported defect that turns out not to be a defect in the product', 'A defect the tool failed to find', 'A defect fixed twice', 'A defect in the test environment'], 0,
    'A high false-positive rate erodes developer trust in the test suite faster than almost anything else.'],
  ['TA-D-003', 'defect-management-systems',
    'Root cause information in a defect report is valuable because it:',
    ['Enables process improvement across future projects', 'Speeds up the current fix', 'Changes the severity', 'Satisfies the tracker workflow'], 0,
    'Individual fixes solve one instance; root cause data is what lets you stop producing the class.'],

  // --- Tools --------------------------------------------------------------
  ['TA-X-001', 'auto-api',
    'A Test Analyst evaluating a test data preparation tool should weigh most heavily:',
    ['Whether it can produce realistic, referentially consistent data at volume', 'Its user interface colours', 'Its licence popularity', 'Whether it is open source'], 0,
    'Data that violates referential integrity produces test failures that teach the team to ignore failures.'],
  ['TA-X-002', 'auto-web-ui',
    'Keyword-driven testing is attractive for a Test Analyst because:',
    ['Test cases can be authored in business terms without scripting', 'It removes the need for maintenance', 'It runs faster than scripted tests', 'It requires no framework'], 0,
    'The trade is that a developer-level engineer must build and maintain the keyword layer underneath.'],
  ['TA-X-003', 'test-documentation',
    'A test management tool adds most value when it:',
    ['Links requirements, tests, runs and defects so coverage is queryable', 'Stores documents', 'Sends email notifications', 'Generates charts'], 0,
    'The traceability graph is the product; charts are a view of it.'],

  // --- Applied analysis ---------------------------------------------------
  ['TA-A-001', 'test-design-techniques',
    'A discount engine: orders over 500 get 10%, loyalty members get an extra 5%, and expired cards are rejected. Which technique gives the most systematic coverage?',
    ['A decision table over the three conditions', 'Boundary value analysis alone', 'State transition testing', 'Exploratory testing alone'], 0,
    'Three independent conditions producing different actions is the textbook shape for a decision table; BVA then covers the 500 boundary inside it.'],
  ['TA-A-002', 'test-design-techniques',
    'A shopping cart keeps items for 30 days. The most valuable boundary tests are around:',
    ['Day 29, 30 and 31 of item age', 'Day 1 only', 'Day 15 only', 'Item price'], 0,
    'The retention rule is the specification; its boundary is where the off-by-one lives, usually in a timezone-sensitive comparison.'],
  ['TA-A-003', 'requirements-testing',
    'A user story says "As an admin I want to export users so that I can analyse them". The most important missing information for a Test Analyst is:',
    ['The acceptance criteria: format, fields, volume limits and permissions', 'The developer assigned', 'The story point estimate', 'The sprint number'], 0,
    'Without those, any export satisfies the story, and any defect report about it is arguable.'],
  ['TA-A-004', 'process-analysis',
    'Escaped defects are concentrated in integrations with third-party services. The most effective analyst response is:',
    ['Add contract and negative tests around those integrations and their failure modes', 'Add more UI end-to-end tests', 'Increase the size of the regression suite', 'Increase exploratory time uniformly'], 0,
    'Target the mitigation at the observed cluster. Uniform increases spend effort where defects are not.'],
  ['TA-A-005', 'testing-types',
    'The system must behave correctly when a downstream service times out. This is primarily:',
    ['Reliability (fault tolerance) testing', 'Usability testing', 'Portability testing', 'Maintainability testing'], 0,
    'Fault tolerance is a reliability sub-characteristic, and it needs deliberate fault injection rather than happy-path testing.'],
  ['TA-A-006', 'test-design-techniques',
    'A field accepts a date range where the end date must not precede the start date. The strongest test set covers:',
    ['End before start, end equal to start, end after start, and both empty', 'Only valid ranges', 'Only the maximum range', 'Only the minimum range'], 0,
    'The rule creates three relational partitions plus the missing-value case, and equal-to-start is the boundary most often implemented wrong.'],
  ['TA-A-007', 'requirements-testing',
    'Two stakeholders describe the same feature differently. The Test Analyst should first:',
    ['Surface the conflict explicitly and get it resolved before designing tests', 'Test both interpretations', 'Pick the more senior stakeholder version', 'Test neither until documentation arrives'], 0,
    'Designing tests over an unresolved conflict guarantees a dispute at the acceptance gate, when it is most expensive.'],
  ['TA-A-008', 'testing-metrics',
    'Which coverage measure is most meaningful to report to a business stakeholder?',
    ['Coverage of prioritised requirements and risks', 'Statement coverage', 'Number of test cases', 'Lines of test code'], 0,
    'Business stakeholders reason about features and risks; code-level coverage is an engineering diagnostic.'],
  ['TA-A-009', 'test-design-techniques',
    'When a specification is missing entirely, the most defensible approach is:',
    ['Exploratory testing under charters, plus documenting the discovered behaviour as a draft oracle', 'Not testing at all', 'Testing only what the developer describes', 'Waiting indefinitely'], 0,
    'The session output becomes the first version of the specification, which is a deliverable in its own right.'],
  ['TA-A-010', 'testing-types',
    'A localisation defect that only appears in Turkish is most likely caused by:',
    ['Case conversion rules (the dotted and dotless i)', 'Screen size', 'Network latency', 'Database indexing'], 0,
    'The Turkish locale breaks naive toUpperCase/toLowerCase comparisons, which is the classic locale-dependent logic defect.'],
]);
