import { defineQuestions } from '../define.js';

/**
 * Middle tier, sourced from the "yellow" rows of the Performance Review sheet.
 */
export const middlePrQuestions = defineQuestions('middle', 'pr-matrix', [
  // --- api-theory ---------------------------------------------------------
  ['MD-API-001', 'api-theory',
    'Why is API-level testing usually cheaper and more stable than the same coverage at UI level?',
    ['It skips rendering and layout, so it is faster and not affected by cosmetic changes', 'It requires no test data', 'It needs no assertions', 'It cannot produce false negatives'], 0,
    'This is the argument behind the test pyramid: push coverage down to the layer with the most stable contract and the fastest feedback.'],
  ['MD-API-002', 'api-theory',
    'Which is the key difference between REST and SOAP?',
    ['REST is an architectural style over HTTP; SOAP is a protocol with a strict XML envelope', 'REST cannot use XML', 'SOAP cannot be tested automatically', 'REST always uses GraphQL'], 0,
    'SOAP brings WSDL, a fixed envelope and built-in standards (WS-Security). REST relies on HTTP semantics and is far lighter, at the cost of a formal contract unless OpenAPI is added.'],
  ['MD-API-003', 'api-theory',
    'What is idempotency and why does it matter when testing a payment API?',
    ['Repeating the same request must not create a second charge', 'The request must always return 200', 'The request must be encrypted', 'The request must complete within one second'], 0,
    'Network retries are routine. An idempotency key on POST is the mechanism that stops one user click becoming two payments.'],
  ['MD-API-004', 'api-theory',
    'Contract testing between two services primarily protects against:',
    ['One service changing its interface in a way that breaks its consumers', 'Slow response times', 'Database corruption', 'UI layout regressions'], 0,
    'Contract tests give the fast, targeted feedback that a full end-to-end suite gives slowly and flakily.'],
  ['MD-API-005', 'api-theory',
    'An API returns 200 OK with a body of {"error": "user not found"}. This is a defect because:',
    ['The status code contradicts the payload, so clients cannot rely on HTTP semantics', 'The body should be XML', '200 is never valid for GET', 'The message is in English'], 0,
    'Clients, proxies, caches and monitoring all key off the status code. Encoding failures in a 200 breaks every one of them.'],
  ['MD-API-006', 'api-theory',
    'When testing pagination on a REST collection endpoint, the most important edge cases are:',
    ['Empty result, single page, exact page boundary and out-of-range page', 'Only the first page', 'Only very large pages', 'Only the sort order'], 0,
    'Off-by-one at the page boundary and behaviour past the last page are where pagination defects actually live.'],

  // --- risks-in-testing ---------------------------------------------------
  ['MD-RISK-001', 'risks-in-testing',
    'Which is the correct order of steps in risk-based testing?',
    ['Identify risks, analyse (likelihood x impact), prioritise, allocate effort, monitor', 'Write test cases, then look for risks', 'Execute tests, then rank the defects found', 'Estimate first, then identify risks'], 0,
    'Risk analysis drives the plan. Running risk analysis after the tests are written turns it into documentation rather than a decision tool.'],
  ['MD-RISK-002', 'risks-in-testing',
    'A project risk, as opposed to a product risk, is:',
    ['The only automation engineer is leaving next month', 'The payment module may miscalculate VAT', 'The app may be slow on 3G', 'The export may lose Unicode characters'], 0,
    'Project risks threaten the ability to deliver; product risks threaten the quality of what is delivered.'],
  ['MD-RISK-003', 'risks-in-testing',
    'The most useful output of a risk workshop for a tester is:',
    ['A prioritised list of risk areas that determines depth of coverage', 'A longer test plan', 'A list of everyone who attended', 'A fixed number of test cases per module'], 0,
    'Risk priority is what converts limited time into a defensible coverage decision.'],
  ['MD-RISK-004', 'risks-in-testing',
    'Residual risk means:',
    ['The risk that remains after the planned mitigation has been applied', 'A risk nobody identified', 'A risk that already occurred', 'A risk with zero impact'], 0,
    'Communicating residual risk honestly at release time is the single most valuable thing a test report does.'],
  ['MD-RISK-005', 'risks-in-testing',
    'Two weeks of testing are cut to one. The risk-based response is to:',
    ['Cut coverage of the lowest-risk areas and report the resulting residual risk', 'Cut the depth of every area equally', 'Cut regression entirely', 'Keep the plan and work overtime'], 0,
    'Uniform cuts damage high-risk coverage as much as low-risk coverage, which is the opposite of what a risk model is for.'],

  // --- testing-metrics ----------------------------------------------------
  ['MD-MET-001', 'testing-metrics',
    'Defect Detection Percentage (DDP) is calculated as:',
    ['Defects found by testing / (defects found by testing + defects found after release)', 'Defects found / test cases executed', 'Defects fixed / defects reported', 'Test cases passed / test cases executed'], 0,
    'DDP measures how much of the total defect population the test process caught, which is one of the few metrics that says something about test effectiveness.'],
  ['MD-MET-002', 'testing-metrics',
    'Which metric is most easily gamed and therefore most dangerous as a target?',
    ['Number of test cases written', 'Defect detection percentage', 'Requirements coverage', 'Escaped defects per release'], 0,
    'Case count rewards splitting one test into ten. Goodhart law applies: a measure that becomes a target stops being a measure.'],
  ['MD-MET-003', 'testing-metrics',
    'Defect density is normally expressed as:',
    ['Defects per size unit, such as per KLOC or per function point', 'Defects per tester', 'Defects per sprint', 'Defects per environment'], 0,
    'Normalising by size lets you compare modules of different sizes and spot the clusters worth extra attention.'],
  ['MD-MET-004', 'testing-metrics',
    'Test coverage of 90% of requirements tells you:',
    ['Which requirements have at least one test, and nothing about test quality', 'That 90% of defects were found', 'That the product is 90% ready', 'That 10% of the code is broken'], 0,
    'Coverage counts links, not rigour. A weak test still marks a requirement covered.'],
  ['MD-MET-005', 'testing-metrics',
    'A burndown of open defects that is flat while the defect find rate falls most likely indicates:',
    ['Fixing capacity, not test capacity, is the bottleneck', 'The product is ready to release', 'Testing has stopped', 'The metric is wrong'], 0,
    'Reading two metrics together turns a chart into a diagnosis. Either one alone is ambiguous.'],

  // --- json ---------------------------------------------------------------
  ['MD-JSON-001', 'json',
    'Which of these is NOT a valid JSON value type?',
    ['Date', 'Number', 'Boolean', 'null'], 0,
    'JSON has objects, arrays, strings, numbers, booleans and null. Dates are transported as strings (usually ISO 8601), which is why timezone defects are so common.'],
  ['MD-JSON-002', 'json',
    'Which JSON snippet is syntactically invalid?',
    ['{"a": 1,}', '{"a": 1}', '{"a": [1, 2]}', '{"a": {"b": null}}'], 0,
    'JSON forbids a trailing comma. Many parsers are lenient, which is exactly why the defect only shows up on one of them.'],
  ['MD-JSON-003', 'json',
    'A JSON Schema is used in API testing to:',
    ['Validate the structure and types of a response automatically', 'Compress the payload', 'Encrypt sensitive fields', 'Generate the UI'], 0,
    'Schema validation catches whole classes of contract regressions with one assertion instead of dozens of field-by-field checks.'],
  ['MD-JSON-004', 'json',
    'Given {"user": {"roles": ["admin", "qa"]}}, which JSONPath selects the second role?',
    ['$.user.roles[1]', '$.user.roles[2]', '$.roles[1]', '$.user[roles][1]'], 0,
    'JSONPath arrays are zero-indexed, so index 1 is the second element.'],
  ['MD-JSON-005', 'json',
    'A numeric id is returned as 9007199254740993 and the JavaScript client shows 9007199254740992. The cause is:',
    ['JavaScript numbers lose precision above 2^53-1', 'The API is broken', 'JSON cannot hold large numbers', 'The client rounded on purpose'], 0,
    'This is why large ids are transported as strings. It is a genuine, reproducible defect worth reporting against the API contract.'],

  // --- unix ---------------------------------------------------------------
  ['MD-UNIX-001', 'unix',
    'Which command shows the last 100 lines of a log and keeps following it?',
    ['tail -n 100 -f app.log', 'head -n 100 app.log', 'cat -f app.log', 'less -f app.log'], 0,
    'tail -f is the standard way to watch a log while reproducing a defect.'],
  ['MD-UNIX-002', 'unix',
    'What does "grep -i -c error app.log" return?',
    ['The count of lines containing "error", case-insensitively', 'The matching lines only', 'The first matching line', 'The file size'], 0,
    '-i ignores case, -c prints the count instead of the lines.'],
  ['MD-UNIX-003', 'unix',
    'Which chmod value gives the owner read/write/execute and everyone else read/execute?',
    ['755', '777', '644', '700'], 0,
    'Digits are owner/group/other; 7 = rwx, 5 = r-x. 777 grants write to everyone and is almost always a misconfiguration.'],
  ['MD-UNIX-004', 'unix',
    'Which command finds which process is listening on port 8080?',
    ['lsof -i :8080  (or ss -ltnp | grep 8080)', 'ps -ef | grep 8080', 'netcat 8080', 'kill -9 8080'], 0,
    'ps only matches the command line. lsof and ss inspect the actual socket table.'],
  ['MD-UNIX-005', 'unix',
    'In a shell pipeline, what does "2>&1" do?',
    ['Redirects standard error into standard output', 'Runs the command twice', 'Redirects output to file 2', 'Suppresses all output'], 0,
    'Without it, stderr bypasses the pipe and never reaches the next command or the log file.'],

  // --- virtualization -----------------------------------------------------
  ['MD-VIRT-001', 'virtualization',
    'The main difference between a container and a virtual machine is that a container:',
    ['Shares the host kernel instead of running a full guest OS', 'Cannot be networked', 'Is always slower', 'Cannot run databases'], 0,
    'Sharing the kernel is what makes containers start in milliseconds and ship in megabytes rather than gigabytes.'],
  ['MD-VIRT-002', 'virtualization',
    'Why are containers valuable for test environments?',
    ['They make the environment reproducible and disposable', 'They remove the need for test data', 'They guarantee no defects', 'They replace CI'], 0,
    'A disposable environment eliminates the "it passed because of yesterday state" class of false results.'],
  ['MD-VIRT-003', 'virtualization',
    'In Docker, what is the difference between an image and a container?',
    ['An image is the immutable template; a container is a running instance of it', 'They are the same', 'A container is stored in a registry', 'An image has a writable layer'], 0,
    'The writable layer belongs to the container. Data written there disappears with the container unless a volume is mounted.'],
  ['MD-VIRT-004', 'virtualization',
    'A test suite passes locally but fails in the container. The first thing to compare is:',
    ['Environment variables, mounted volumes, timezone and locale', 'The tester keyboard layout', 'The Docker logo version', 'The host screen resolution'], 0,
    'Timezone and locale differences alone account for a large share of container-only failures in date and number formatting.'],
  ['MD-VIRT-005', 'virtualization',
    'docker-compose is most useful in testing for:',
    ['Bringing up an application plus its dependencies as one reproducible stack', 'Running unit tests faster', 'Replacing the CI server', 'Generating test data'], 0,
    'App plus database plus queue plus mock services, started identically on every machine, is exactly the integration-test problem compose solves.'],

  // --- auto-web-ui --------------------------------------------------------
  ['MD-AWEB-001', 'auto-web-ui',
    'The Page Object pattern primarily improves:',
    ['Maintainability, by keeping locators and page behaviour in one place', 'Execution speed', 'Defect detection rate', 'Browser compatibility'], 0,
    'When a locator changes, one file changes. Without it, the same selector is scattered across dozens of tests.'],
  ['MD-AWEB-002', 'auto-web-ui',
    'Which wait strategy produces the most reliable UI tests?',
    ['Explicit waits on a specific expected condition', 'Fixed Thread.sleep calls', 'Implicit waits set globally to a large value', 'No waits at all'], 0,
    'Explicit conditions state what you are waiting for, so the test fails with a meaningful message instead of after an arbitrary timeout.'],
  ['MD-AWEB-003', 'auto-web-ui',
    'A UI test fails once in every ten runs with no product change. The correct handling is:',
    ['Diagnose the race condition and fix it, quarantining the test meanwhile', 'Add a retry so it goes green', 'Increase every sleep', 'Delete the test'], 0,
    'Blanket retries hide real intermittent product defects, which are exactly the ones users report and nobody can reproduce.'],
  ['MD-AWEB-004', 'auto-web-ui',
    'Which locator strategy is generally the most brittle?',
    ['An absolute XPath through the DOM hierarchy', 'A dedicated data-testid', 'An element id', 'An accessible role plus name'], 0,
    'Absolute XPath encodes the entire document structure, so any wrapper div added by a designer breaks it.'],
  ['MD-AWEB-005', 'auto-web-ui',
    'In the test pyramid, UI end-to-end tests should be:',
    ['The smallest layer, covering critical user journeys only', 'The largest layer', 'The only layer', 'Equal in size to unit tests'], 0,
    'E2E tests are the slowest and most brittle per unit of coverage, so they are spent on the journeys that must never break.'],

  // --- auto-mobile-ui -----------------------------------------------------
  ['MD-AMOB-001', 'auto-mobile-ui',
    'Appium is able to drive both Android and iOS because it:',
    ['Speaks the WebDriver protocol on top of each platform native automation framework', 'Recompiles the application', 'Requires the source code', 'Only works on emulators'], 0,
    'Appium wraps UiAutomator2/Espresso on Android and XCUITest on iOS behind one client API.'],
  ['MD-AMOB-002', 'auto-mobile-ui',
    'A key limitation of testing exclusively on emulators and simulators is that they cannot faithfully reproduce:',
    ['Real hardware behaviour: sensors, performance, battery, network conditions', 'Screen layout', 'Button taps', 'Application logic'], 0,
    'Layout and logic transfer well. Performance, thermal behaviour and radio conditions do not, which is why a real-device tier is required.'],
  ['MD-AMOB-003', 'auto-mobile-ui',
    'Which mobile automation problem is caused by the platform rather than by the test code?',
    ['Permission dialogs appearing on a fresh install', 'A misspelled locator', 'A missing assertion', 'A hardcoded sleep'], 0,
    'System dialogs sit outside the app view hierarchy and must be handled explicitly in the automation setup.'],

  // --- auto-performance ---------------------------------------------------
  ['MD-APERF-001', 'auto-performance',
    'The difference between load testing and stress testing is that stress testing:',
    ['Pushes the system beyond its expected capacity to find the breaking point', 'Uses the expected number of users', 'Runs for a long duration at normal load', 'Measures only response time'], 0,
    'Load = expected volume; stress = beyond it; soak/endurance = normal load for a long time; spike = sudden jumps.'],
  ['MD-APERF-002', 'auto-performance',
    'Reporting only the average response time is misleading because:',
    ['It hides the tail; percentiles show what the slowest users actually experience', 'Averages cannot be computed reliably', 'It ignores the number of requests', 'It requires more data'], 0,
    'A 200 ms mean can coexist with a 4 s 99th percentile. Users experience the tail, not the mean.'],
  ['MD-APERF-003', 'auto-performance',
    'A soak (endurance) test is designed to reveal:',
    ['Memory leaks and resource exhaustion over time', 'The maximum throughput', 'The breaking point', 'The cold start time'], 0,
    'Degradation that only appears after hours of steady traffic is invisible to a 10-minute load test.'],
  ['MD-APERF-004', 'auto-performance',
    'Which is a prerequisite for a meaningful performance test?',
    ['A production-like environment and realistic data volume', 'A brand-new empty database', 'A single test user', 'Running from a developer laptop'], 0,
    'Performance is dominated by data volume, indexes, caches and infrastructure. An empty database measures nothing useful.'],

  // --- auto-api -----------------------------------------------------------
  ['MD-AAPI-001', 'auto-api',
    'Which assertion set is the minimum for a meaningful automated API test?',
    ['Status code, response schema and the business-critical field values', 'Status code only', 'Response time only', 'That the response is not empty'], 0,
    'Status alone passes on a 200 with a wrong body; schema alone passes on schema-valid nonsense.'],
  ['MD-AAPI-002', 'auto-api',
    'When automating a REST API, authentication tokens should be:',
    ['Obtained at setup and injected from configuration or a secret store', 'Hardcoded in the test file', 'Committed to the repository', 'Copied from the browser manually each run'], 0,
    'Hardcoded tokens expire, leak and break the suite for everyone else.'],
  ['MD-AAPI-003', 'auto-api',
    'Automated API tests should clean up the data they create because:',
    ['Accumulated state makes later runs non-deterministic', 'Storage is expensive', 'The API requires it', 'It speeds up the tests'], 0,
    'Setup and teardown per test are what make a suite runnable a thousand times with the same result.'],
  ['MD-AAPI-004', 'auto-api',
    'Which negative case is most often missing from API test suites?',
    ['Malformed payloads and wrong content types', 'The happy path', 'A valid GET request', 'A successful login'], 0,
    'Error handling is where APIs leak stack traces, return 500 for client errors and expose internal field names.'],

  // --- auto-db ------------------------------------------------------------
  ['MD-ADB-001', 'auto-db',
    'An automated database test should verify that:',
    ['The persisted data matches the business rules after the operation', 'The UI displays a green message', 'The query executes without syntax errors only', 'The table exists'], 0,
    'The point of a DB-level check is to confirm what was actually stored, independent of what the UI chose to display.'],
  ['MD-ADB-002', 'auto-db',
    'Which practice keeps automated DB tests independent of each other?',
    ['Each test creates its own data and rolls back or deletes it afterwards', 'Tests share one fixed dataset', 'Tests run in a fixed alphabetical order', 'Tests read production data'], 0,
    'Shared mutable state makes a suite order-dependent, which is the hardest kind of flakiness to diagnose.'],
  ['MD-ADB-003', 'auto-db',
    'Testing a database migration should always include:',
    ['A rollback path and a check on existing production-like data', 'Only the forward migration on an empty schema', 'Only a syntax check', 'Only performance measurement'], 0,
    'Migrations fail on real data, not on empty schemas, and a migration without a tested rollback is an unrecoverable deployment.'],

  // --- precise-estimation -------------------------------------------------
  ['MD-PEST-001', 'precise-estimation',
    'Three-point estimation (optimistic, most likely, pessimistic) is useful because it:',
    ['Expresses uncertainty explicitly instead of hiding it in one number', 'Always produces a smaller estimate', 'Removes the need for historical data', 'Guarantees the deadline'], 0,
    'The spread itself is information: a wide range is a signal that the requirement needs clarification before it is committed.'],
  ['MD-PEST-002', 'precise-estimation',
    'The most reliable input to a testing estimate is:',
    ['Historical actuals from comparable work in the same context', 'Management expectation', 'The developer estimate multiplied by a fixed factor', 'A round number that sounds credible'], 0,
    'Calibration against your own past data beats every rule of thumb, because it silently includes your team overheads.'],
  ['MD-PEST-003', 'precise-estimation',
    'When estimating a bug fix verification, you should include:',
    ['Retest of the fix plus regression around the affected area', 'Retest of the fix only', 'The developer fixing time', 'Nothing, it is negligible'], 0,
    'The regression radius, not the retest, is the part that varies from ten minutes to two days.'],
  ['MD-PEST-004', 'precise-estimation',
    'Planning poker reduces estimation bias mainly by:',
    ['Having estimators commit independently before discussion', 'Averaging everyone number', 'Letting the most senior person decide', 'Using Fibonacci values'], 0,
    'Simultaneous reveal is the mechanism; the card values are just a scale. Anchoring is what it defends against.'],

  // --- process-analysis ---------------------------------------------------
  ['MD-PROC-001', 'process-analysis',
    'A high number of defects escaping to production while the internal pass rate is high indicates:',
    ['The tests do not cover what users actually do', 'Testers are working too slowly', 'The product is too complex', 'Developers write bad code'], 0,
    'A high pass rate with high escape rate is a coverage and oracle problem, and it is measurable through DDP.'],
  ['MD-PROC-002', 'process-analysis',
    'Root cause analysis of escaped defects is most useful when it produces:',
    ['A process change that prevents the same class of defect', 'A list of who made the mistake', 'A longer regression suite', 'A new metric'], 0,
    'RCA that ends in a name changes nothing. RCA that ends in a changed review, check or gate changes the outcome.'],
  ['MD-PROC-003', 'process-analysis',
    'The testing process takes longer every sprint although scope is constant. The most likely cause to investigate first is:',
    ['Growing regression suite and manual repetition', 'Testers becoming slower', 'Requirements getting harder', 'Tooling licence limits'], 0,
    'Regression cost grows monotonically with product size unless it is actively automated or pruned.'],
  ['MD-PROC-004', 'process-analysis',
    'Which is a symptom of a testing process problem rather than a product problem?',
    ['The same defect is reported by three testers independently', 'A module has high defect density', 'A performance target is missed', 'A requirement is ambiguous'], 0,
    'Duplicate reports mean coverage is uncoordinated and the tracker is not being searched - both process issues.'],

  // --- project-estimation -------------------------------------------------
  ['MD-PROJ-001', 'project-estimation',
    'When estimating testing for a whole project, which is most often underestimated?',
    ['Environment setup, test data and communication overhead', 'Test case execution', 'Test case writing', 'Defect reporting'], 0,
    'Execution is visible and easy to count; the surrounding work is invisible and dominates the variance.'],
  ['MD-PROJ-002', 'project-estimation',
    'A customer asks for a fixed-price testing estimate on a project with unstable requirements. The professional response is:',
    ['Propose a timeboxed discovery phase or a range with explicit assumptions', 'Give a low number to win the deal', 'Give a very high number to be safe', 'Refuse to quote'], 0,
    'Both a lowball and a padded number destroy trust later. Naming the assumption is what makes the number defensible.'],
  ['MD-PROJ-003', 'project-estimation',
    'Which factor most increases a testing estimate for the same feature set?',
    ['A regulated domain requiring evidence and traceability', 'A larger monitor', 'A newer test tool', 'More frequent stand-ups'], 0,
    'Compliance overhead - documented evidence, sign-offs, audit trails - can double the cost of identical functional coverage.'],

  // --- onboarding-training ------------------------------------------------
  ['MD-ONB-001', 'onboarding-training',
    'The most effective first week for a new tester on a project is:',
    ['A guided tour of the domain plus a small real task with a named mentor', 'Reading all documentation alone', 'Immediately owning the regression suite', 'Waiting until the next sprint starts'], 0,
    'A real task with support produces competence and confidence far faster than passive reading.'],
  ['MD-ONB-002', 'onboarding-training',
    'When a mentee reports a defect that is actually correct behaviour, the best response is to:',
    ['Walk through the requirement together so they learn to find the oracle', 'Close it silently', 'Tell them to be more careful', 'Ask someone else to review their reports from now on'], 0,
    'The goal is a tester who checks the oracle next time, not one who reports less.'],
  ['MD-ONB-003', 'onboarding-training',
    'A good measure that onboarding worked is:',
    ['The new tester completes representative tasks with decreasing supervision', 'The number of documents they read', 'The number of meetings attended', 'How quickly they stopped asking questions'], 0,
    'Questions stopping can mean understanding or disengagement. Independent delivery on real work distinguishes the two.'],

  // --- test-doc-development -----------------------------------------------
  ['MD-TDOC-001', 'test-doc-development',
    'When designing a test documentation structure for a new project, the first decision should be:',
    ['How much documentation the context and risk actually justify', 'Which template the last project used', 'Which tool the team prefers', 'How many test cases to write per module'], 0,
    'A regulated medical product and an internal admin tool need different amounts of evidence. Copying a template skips that judgement.'],
  ['MD-TDOC-002', 'test-doc-development',
    'A documentation standard is worth introducing mainly because it:',
    ['Makes test artefacts reviewable and reusable across the team', 'Makes documents longer', 'Satisfies the customer', 'Reduces the need for testing'], 0,
    'The benefit is that a case written by one tester can be executed and maintained by another without a conversation.'],
  ['MD-TDOC-003', 'test-doc-development',
    'The strongest argument for keeping test documentation in a version-controlled, tool-supported form is:',
    ['Changes are traceable and documentation evolves with the product', 'It looks more professional', 'It uses less disk space', 'It is required by ISTQB'], 0,
    'Untracked documents drift silently; tracked ones make the drift visible and reviewable.'],

  // --- customer-test-reports ----------------------------------------------
  ['MD-CREP-001', 'customer-test-reports',
    'A test report intended for a customer should lead with:',
    ['An assessment of product quality and the risks of releasing', 'The number of test cases executed', 'The list of testers involved', 'The tools used'], 0,
    'The customer needs to make a release decision. Everything else is supporting detail.'],
  ['MD-CREP-002', 'customer-test-reports',
    'Which statement belongs in a customer-facing quality assessment?',
    ['Checkout and payment are stable; reporting has 3 open major defects affecting export',
     'We executed 412 test cases',
     'Two testers were on holiday',
     'The build server was slow on Tuesday'], 0,
    'Name the areas, their state and the concrete risk. Internal logistics do not belong in a quality assessment.'],
  ['MD-CREP-003', 'customer-test-reports',
    'You must report that a critical defect remains open the day before release. The right approach is to:',
    ['State the defect, its impact, the workaround and the options, without softening the risk', 'Omit it to avoid alarming the customer', 'Mention it verbally only', 'Report it as medium severity'], 0,
    'Concealing known risk at a release gate is the fastest way to lose a client permanently, and it removes their right to decide.'],
  ['MD-CREP-004', 'customer-test-reports',
    'Test reports should be issued:',
    ['On a regular agreed cadence and at every release decision point', 'Only when something goes wrong', 'Only at the end of the project', 'Only when the customer asks'], 0,
    'Predictable reporting builds trust; reports that appear only with bad news train the reader to dread them.'],
]);
