import { defineQuestions } from '../define.js';

/**
 * Senior tier, sourced from the "red" rows of the Performance Review sheet.
 */
export const seniorPrQuestions = defineQuestions('senior', 'pr-matrix', [
  // --- estimates-forecasts ------------------------------------------------
  ['SR-FC-001', 'estimates-forecasts',
    'A forecast differs from an estimate in that a forecast:',
    ['Projects a future outcome from observed trend data', 'Is always more accurate', 'Requires no assumptions', 'Is produced only by managers'], 0,
    'An estimate is a judgement about work not yet started; a forecast extrapolates from what is already being observed, such as burn rate or defect arrival.'],
  ['SR-FC-002', 'estimates-forecasts',
    'Defect arrival is still rising three days before the planned release. The most defensible forecast statement is:',
    ['Discovery has not saturated; the current date carries material risk, with these options', 'We will be ready, the team will work harder', 'We cannot say anything until the last day', 'Testing is complete'], 0,
    'A rising arrival curve is evidence that discovery is incomplete. Reporting the shape of the curve converts a gut feeling into a defensible position.'],
  ['SR-FC-003', 'estimates-forecasts',
    'Which is the strongest basis for a testing forecast?',
    ['Historical velocity and defect data from comparable releases of the same product', 'Industry benchmark ratios', 'The project manager preference', 'The size of the requirements document'], 0,
    'Your own history includes your team overheads, your domain and your codebase - none of which a benchmark ratio knows.'],
  ['SR-FC-004', 'estimates-forecasts',
    'Cone-of-uncertainty reasoning implies that an estimate given at project start should be:',
    ['Expressed as a wide range and re-forecast as information accrues', 'Given as a single committed number', 'Refused', 'Doubled as a safety margin'], 0,
    'A single number at the widest point of the cone is a commitment made with the least information anyone will ever have.'],

  // --- dev-algorithms -----------------------------------------------------
  ['SR-ALG-001', 'dev-algorithms',
    'A search that takes 1 ms on 1,000 records and 1 s on 1,000,000 records most likely has complexity:',
    ['O(n)', 'O(1)', 'O(log n)', 'O(n^2)'], 0,
    'A 1000x increase in data producing a 1000x increase in time is linear. O(n^2) would have grown a millionfold.'],
  ['SR-ALG-002', 'dev-algorithms',
    'Why does algorithmic complexity matter to a senior tester?',
    ['It predicts which features will degrade as production data grows', 'It determines the UI layout', 'It replaces performance testing', 'It defines the test levels'], 0,
    'Knowing that a feature is quadratic tells you to test it at production volume rather than with 20 rows.'],
  ['SR-ALG-003', 'dev-algorithms',
    'A test that passes on 10 records and times out on 100,000 indicates:',
    ['A scalability defect that must be reported with the volume that triggers it', 'A test data problem only', 'A flaky test', 'Nothing, the volume is unrealistic'], 0,
    'The volume is only unrealistic until production reaches it. Report it with the threshold you measured.'],
  ['SR-ALG-004', 'dev-algorithms',
    'Reading the implementation before designing tests is most defensible when:',
    ['You are designing structural tests or hunting for a suspected defect class', 'You want to save time on analysis', 'The specification exists and is clear', 'You are doing acceptance testing'], 0,
    'Code knowledge biases black-box design towards what was built. It is a deliberate tool for white-box work, not a default.'],

  // --- vcs ----------------------------------------------------------------
  ['SR-VCS-001', 'vcs',
    'What does "git rebase" do that "git merge" does not?',
    ['Replays commits onto a new base, producing linear history and new commit hashes', 'Deletes branches', 'Pushes to the remote', 'Resolves conflicts automatically'], 0,
    'Because hashes change, rebasing a branch other people have pulled rewrites shared history and breaks their checkouts.'],
  ['SR-VCS-002', 'vcs',
    'Why should automated tests live in the same repository as the code they test?',
    ['A single commit keeps code and its tests in a consistent, reviewable state', 'It saves disk space', 'It is faster to clone', 'Tools require it'], 0,
    'Split repositories drift: the test suite at HEAD no longer corresponds to any particular version of the product.'],
  ['SR-VCS-003', 'vcs',
    'Trunk-based development affects testing mainly because it:',
    ['Requires fast, reliable automated checks on every small merge to main', 'Removes the need for regression testing', 'Eliminates merge conflicts', 'Requires long-lived feature branches'], 0,
    'The whole model depends on a pipeline trustworthy enough to gate main. Without it, trunk-based development just breaks main faster.'],
  ['SR-VCS-004', 'vcs',
    'A feature flag lets a team:',
    ['Merge incomplete work to main while keeping it disabled in production', 'Skip testing the feature', 'Avoid version control', 'Deploy without a pipeline'], 0,
    'Flags create a combinatorial test surface of their own: on, off, and the transition between them with existing data.'],

  // --- static-analysis ----------------------------------------------------
  ['SR-SA-001', 'static-analysis',
    'A static analysis gate in CI is most valuable when it:',
    ['Fails the build on new violations while tolerating the existing baseline', 'Reports thousands of legacy warnings on every run', 'Runs only before release', 'Is advisory only'], 0,
    'Ratcheting on new code makes the gate actionable. A wall of legacy warnings trains everyone to ignore it.'],
  ['SR-SA-002', 'static-analysis',
    'Which defect class is static analysis genuinely good at finding?',
    ['Null dereferences, resource leaks and injection-prone string concatenation', 'Wrong business rules', 'Poor usability', 'Missing requirements'], 0,
    'Static tools reason about structure and data flow. They have no oracle for intent.'],
  ['SR-SA-003', 'static-analysis',
    'A high false-positive rate in a static analysis tool is dangerous because:',
    ['Developers start suppressing findings wholesale, including the true ones', 'The build gets slower', 'It uses more licences', 'It duplicates code review'], 0,
    'Tuning the ruleset down to a trusted core is more valuable than enabling every rule available.'],
  ['SR-SA-004', 'static-analysis',
    'Code coverage measured by unit tests should be treated as:',
    ['A diagnostic that finds untested code, not a quality target', 'A contractual quality guarantee', 'A replacement for review', 'A measure of defect density'], 0,
    'Coverage as a mandated target reliably produces assertion-free tests that execute code without checking anything.'],

  // --- unit-tests ---------------------------------------------------------
  ['SR-UT-001', 'unit-tests',
    'A good unit test is characterised by:',
    ['Fast, isolated, deterministic and testing one behaviour', 'Covering the whole system end to end', 'Using the real database', 'Depending on the previous test'], 0,
    'The FIRST properties. A unit test that touches the network is an integration test wearing the wrong label.'],
  ['SR-UT-002', 'unit-tests',
    'The difference between a stub and a mock is that a mock:',
    ['Also verifies that the expected interactions occurred', 'Is always slower', 'Cannot return values', 'Is used only in UI tests'], 0,
    'A stub supplies canned answers; a mock additionally asserts on how it was called. Over-mocking couples tests to implementation.'],
  ['SR-UT-003', 'unit-tests',
    'When a senior tester reviews a unit test suite, the strongest warning sign is:',
    ['Tests with high coverage but few meaningful assertions', 'Tests that use fixtures', 'Tests grouped by class', 'Tests with descriptive names'], 0,
    'Coverage without assertions is the classic way to hit a mandated number while verifying nothing.'],
  ['SR-UT-004', 'unit-tests',
    'Test-driven development influences design because:',
    ['Code that is hard to test tends to get refactored towards looser coupling', 'It removes the need for design', 'It guarantees no defects', 'It replaces integration testing'], 0,
    'The design pressure is the main long-term benefit; the tests themselves are a valuable by-product.'],

  // --- test-frameworks ----------------------------------------------------
  ['SR-TF-001', 'test-frameworks',
    'When designing a custom test framework, the most important early decision is:',
    ['The layering: tests, business actions, and technical driver kept separate', 'The programming language', 'The report colour scheme', 'The number of test cases'], 0,
    'Layering is what lets the driver be replaced without rewriting tests. It is also the decision that is most expensive to change later.'],
  ['SR-TF-002', 'test-frameworks',
    'A framework should provide a shared reporting and logging layer mainly because:',
    ['Failure diagnosis time dominates the cost of a large suite', 'Reports look professional', 'It is required by CI', 'It reduces the number of tests'], 0,
    'A failure that takes 30 minutes to diagnose, times a hundred failures, is where automation budgets actually go.'],
  ['SR-TF-003', 'test-frameworks',
    'Which is the strongest argument against building a custom framework from scratch?',
    ['The maintenance cost is permanent and falls on your team alone', 'Custom code is always slower', 'It cannot integrate with CI', 'It cannot be documented'], 0,
    'Every custom abstraction is a product you now own, including its documentation, onboarding and defects.'],
  ['SR-TF-004', 'test-frameworks',
    'Parallel execution support must be designed in from the start because:',
    ['Shared state and fixed test data make retrofitting parallelism very expensive', 'It is a licence requirement', 'It changes the language', 'Reports cannot be merged otherwise'], 0,
    'Data isolation and statelessness are architectural properties. Adding them to a mature suite usually means rewriting its fixtures.'],

  // --- test-plan ----------------------------------------------------------
  ['SR-TP-001', 'test-plan',
    'The most important section of a test plan for stakeholders is usually:',
    ['Scope, risks and exit criteria', 'The tool list', 'The team CVs', 'The document revision history'], 0,
    'Those three answer what will and will not be tested, what could go wrong, and how we will know we are done.'],
  ['SR-TP-002', 'test-plan',
    'A test plan that is never updated during the project is:',
    ['A document about a project that no longer exists', 'Still fully useful', 'Ideal, since it is stable', 'Required by ISTQB'], 0,
    'Plans are living artefacts. An unchanged plan through a changing project means nobody is using it to decide anything.'],
  ['SR-TP-003', 'test-plan',
    'Exit criteria should be defined:',
    ['Before execution starts, together with the stakeholders who will use them', 'At the end, based on what was achieved', 'By the test team alone', 'Only for regulated projects'], 0,
    'Criteria written after the fact describe the outcome instead of governing it, and they cannot support a release argument.'],
  ['SR-TP-004', 'test-plan',
    'Which item belongs in the test plan rather than in the test strategy?',
    ['The specific environments and schedule for this release', 'The organisation-wide approach to automation', 'The general defect classification scheme', 'The company testing policy'], 0,
    'Strategy is organisation-level and durable; the plan is project-level and time-bound.'],

  // --- process-optimization -----------------------------------------------
  ['SR-OPT-001', 'process-optimization',
    'The regression suite takes 8 hours and blocks daily releases. The best first optimisation is:',
    ['Identify and parallelise or prune the slowest, lowest-value tests using risk and history', 'Delete half the tests', 'Run it weekly instead', 'Add more testers'], 0,
    'Measure first: suite time is usually dominated by a small number of tests, and value is usually concentrated elsewhere.'],
  ['SR-OPT-002', 'process-optimization',
    'Before optimising a testing process you should:',
    ['Measure the current baseline so improvement can be demonstrated', 'Change the tooling', 'Reorganise the team', 'Increase the number of test cases'], 0,
    'Without a baseline, an "improvement" is an opinion, and it cannot be defended when the next deadline arrives.'],
  ['SR-OPT-003', 'process-optimization',
    'A senior tester proposes automating a manual suite. The strongest justification is:',
    ['A calculated payback based on run frequency, stability and maintenance cost', 'Automation is a best practice', 'Manual testing is boring', 'Competitors automate'], 0,
    'Automation that runs twice a year rarely repays its maintenance. The frequency and stability numbers make or break the case.'],
  ['SR-OPT-004', 'process-optimization',
    'Which change most reliably shortens feedback time in a mature process?',
    ['Moving coverage down the pyramid from UI to API and unit level', 'Adding more end-to-end tests', 'Hiring more manual testers', 'Increasing the sprint length'], 0,
    'The same behaviour verified at a lower level runs in seconds instead of minutes and fails for one identifiable reason.'],

  // --- team-reports -------------------------------------------------------
  ['SR-TR-001', 'team-reports',
    'A monthly test report for a whole team should be built around:',
    ['Product quality trends, risk and impediments over the period', 'Individual tester output', 'The number of meetings', 'The list of executed cases'], 0,
    'The audience is deciding about the product and the process, not evaluating individuals.'],
  ['SR-TR-002', 'team-reports',
    'Which trend is the strongest early warning in a release report?',
    ['Defect arrival rate that has not yet flattened', 'Total defect count', 'Number of test cases executed', 'Hours logged'], 0,
    'A non-saturating arrival curve says discovery is incomplete, whatever the absolute counts look like.'],
  ['SR-TR-003', 'team-reports',
    'Reporting individual defect counts per tester in a team report is problematic because:',
    ['It incentivises volume and discourages helping teammates', 'It takes time to collect', 'It is not accurate', 'Managers do not read it'], 0,
    'It converts a collaborative activity into a competition measured by the least meaningful available number.'],
  ['SR-TR-004', 'team-reports',
    'When a report must deliver bad news, the most effective structure is:',
    ['Situation, impact, options with trade-offs, and a recommendation', 'The bad news alone', 'The good news first and the bad news buried', 'A request for more time'], 0,
    'Arriving with options rather than only a problem is what distinguishes a senior report from an escalation.'],

  // --- presale ------------------------------------------------------------
  ['SR-PRE-001', 'presale',
    'During a presale call the customer asks for a firm testing price with almost no information. The strongest professional response is:',
    ['Offer a discovery phase, plus a ranged indication with the assumptions stated', 'Quote a low figure to secure the deal', 'Quote a very high figure to be safe', 'Decline to answer'], 0,
    'A number given without a basis becomes an expectation you cannot meet, and the correction costs more trust than the delay would have.'],
  ['SR-PRE-002', 'presale',
    'The most persuasive presale material for a QA service is usually:',
    ['A relevant case study with the problem, approach and measured outcome', 'A list of tools', 'The team size', 'The number of years in business'], 0,
    'Buyers are matching your evidence against their own problem. Tool lists say nothing about outcomes.'],
  ['SR-PRE-003', 'presale',
    'A prospect asks for something your team cannot deliver well. You should:',
    ['Say so plainly and propose the closest thing you can deliver well', 'Agree and figure it out later', 'Refer them to a competitor immediately', 'Ignore the question'], 0,
    'Overcommitting in presale is repaid with interest during delivery, usually by the people who were not in the room.'],
  ['SR-PRE-004', 'presale',
    'Which question is most valuable to ask a prospect early?',
    ['What does a successful outcome look like to you in six months?', 'Which tools do you use?', 'How large is your team?', 'What is your budget?'], 0,
    'The success definition is what lets you scope, price and later demonstrate value. Everything else is detail underneath it.'],

  // --- team-test-planning -------------------------------------------------
  ['SR-TTP-001', 'team-test-planning',
    'When planning testing for an entire team across several parallel streams, the primary constraint to model is:',
    ['Shared bottlenecks: environments, test data and specialised skills', 'Individual preferences', 'Number of test cases', 'Office seating'], 0,
    'Parallel streams fail on shared resources long before they fail on headcount.'],
  ['SR-TTP-002', 'team-test-planning',
    'Two streams need the same test environment in the same week. The best plan is:',
    ['Sequence them explicitly, or provision an isolated environment, and state the cost', 'Let the teams work it out', 'Ignore it and react when it happens', 'Cancel one stream'], 0,
    'Surfacing the conflict as a decision with a price is the planning act; leaving it implicit guarantees a lost week.'],
  ['SR-TTP-003', 'team-test-planning',
    'A team plan should allocate contingency because:',
    ['Defect fixing, retesting and environment issues are certain but not schedulable', 'It makes the plan look longer', 'The customer expects it', 'It is a standard percentage'], 0,
    'Contingency is not padding; it is the budget for known-uncertain work, and it should be named as such.'],

  // --- role-distribution --------------------------------------------------
  ['SR-ROLE-001', 'role-distribution',
    'Assigning roles inside a test team should be driven primarily by:',
    ['Project risk and required skills, balanced against individual growth', 'Seniority alone', 'Who volunteers first', 'Alphabetical rotation'], 0,
    'Risk decides what must be covered by experience; growth decides where to place the person who will be senior next year.'],
  ['SR-ROLE-002', 'role-distribution',
    'A single person is the only one who can run the performance suite. This is:',
    ['A key-person risk that should be mitigated by cross-training', 'Efficient specialisation to preserve', 'A staffing budget issue', 'Not a testing concern'], 0,
    'Bus factor one on a critical capability is a project risk and belongs in the risk register.'],
  ['SR-ROLE-003', 'role-distribution',
    'Rotating testers across modules periodically helps because:',
    ['Fresh eyes find defects that familiarity hides, and knowledge spreads', 'It is fairer', 'It reduces documentation', 'It shortens onboarding'], 0,
    'It costs some ramp-up time and buys both defect detection and resilience.'],

  // --- people-management --------------------------------------------------
  ['SR-PM-001', 'people-management',
    'A team member consistently misses estimates. The most effective first step is:',
    ['A private conversation to understand the cause before acting', 'Reducing their estimates for them', 'Raising it in the team retrospective by name', 'Reassigning all their work'], 0,
    'The cause could be skill, scope, blockers or estimation technique, and each has a different remedy. Public correction addresses none of them.'],
  ['SR-PM-002', 'people-management',
    'Effective feedback to a team member is:',
    ['Specific, timely, about observable behaviour and its impact', 'General and delivered annually', 'Given in front of the team', 'Focused on personality'], 0,
    'Behaviour plus impact is actionable; personality is not, and the person cannot do anything with it.'],
  ['SR-PM-003', 'people-management',
    'Two testers disagree publicly about test coverage. As their lead you should:',
    ['Facilitate a decision based on risk and evidence, then record it', 'Decide for them immediately', 'Let them continue until one gives up', 'Escalate to the customer'], 0,
    'A recorded, evidence-based decision resolves the current dispute and gives the team a precedent for the next one.'],
  ['SR-PM-004', 'people-management',
    'The main purpose of a one-to-one with a team member is:',
    ['To understand blockers, growth and context that status meetings never surface', 'To review their task list', 'To deliver performance ratings', 'To assign new work'], 0,
    'Status is already visible on the board. The one-to-one is for what the board cannot show.'],

  // --- risk-management ----------------------------------------------------
  ['SR-RM-001', 'risk-management',
    'A risk register entry is complete when it contains:',
    ['Description, likelihood, impact, owner, mitigation and contingency', 'Description and severity', 'Description only', 'Description and a due date'], 0,
    'Without an owner and a contingency, a register is a list of worries rather than a management tool.'],
  ['SR-RM-002', 'risk-management',
    'The difference between mitigation and contingency is that mitigation:',
    ['Reduces likelihood or impact in advance; contingency is the plan if it happens anyway', 'Is cheaper', 'Applies only to project risks', 'Is the same thing'], 0,
    'Well-run projects fund both, because mitigation is never complete.'],
  ['SR-RM-003', 'risk-management',
    'A high-likelihood, high-impact risk with no mitigation should be:',
    ['Escalated immediately with options and a recommendation', 'Monitored quietly', 'Accepted silently', 'Removed from the register'], 0,
    'Escalation with options is the deliverable; escalation with only a problem transfers work upwards without transferring information.'],
  ['SR-RM-004', 'risk-management',
    'Which risk response is being applied when a team buys a device cloud rather than maintaining its own device lab?',
    ['Transfer', 'Avoid', 'Accept', 'Exploit'], 0,
    'The operational risk moves to the supplier. The residual risk (supplier availability) should then be recorded.'],
  ['SR-RM-005', 'risk-management',
    'Risk-based test prioritisation breaks down when:',
    ['Risk assessments are made once and never revisited as the product changes', 'Risks are documented', 'Stakeholders are involved', 'Impact is estimated'], 0,
    'A stale risk model directs effort at last quarter product, which is indistinguishable from no risk model at all.'],
]);
