import { defineQuestions } from '../define.js';

/**
 * ISTQB Advanced Level - Test Analyst material at the Senior tier: the
 * judgement-heavy end of the syllabus, where the answer depends on weighing
 * risk, cost and evidence rather than on recalling a technique.
 */
export const seniorCtalTaQuestions = defineQuestions('senior', 'istqb-ctal-ta', [
  ['STA-001', 'test-design-techniques',
    'A legacy module has no specification, no tests and a high escaped-defect rate. The most effective analyst strategy is:',
    ['Build a defect taxonomy from its history and design defect-based tests around it', 'Write exhaustive tests from the code', 'Rewrite the specification first', 'Rely on exploratory testing alone'], 0,
    'The escaped-defect history is the best available oracle in the absence of a specification, and a taxonomy converts it into repeatable coverage.'],
  ['STA-002', 'risks-in-testing',
    'A risk assessment rates two areas equally. The tie-break most consistent with risk-based testing is:',
    ['Detectability: prefer the area where a defect would reach production unnoticed', 'Alphabetical order', 'Whichever is easier to test', 'Whichever the developer prefers'], 0,
    'Some risk models add detectability as a third factor precisely because an undetectable failure has a much higher effective impact.'],
  ['STA-003', 'test-design-techniques',
    'When is it justified to reduce a decision table by collapsing rules?',
    ['When a condition demonstrably cannot affect the outcome for those rules', 'Whenever the table is large', 'When time is short', 'When the developer says so'], 0,
    'Collapsing on a demonstrated independence is analysis; collapsing under time pressure is guessing with extra steps.'],
  ['STA-004', 'testing-types',
    'A feature passes all functional tests but users abandon it at a specific step. The most appropriate next investigation is:',
    ['Usability evaluation of that step with real users or task analysis', 'More functional test cases', 'Performance testing', 'Static analysis'], 0,
    'The functional oracle is satisfied; the failure is in appropriateness and usability, which functional tests cannot observe.'],
  ['STA-005', 'process-analysis',
    'Escaped defects cluster in areas that were tested last, close to the deadline. The structural fix is:',
    ['Reorder the plan so high-risk areas are tested first, not last', 'Extend the schedule', 'Add testers at the end', 'Increase the regression suite'], 0,
    'Testing high risk last means the least time to react to what you find. It is a planning defect, not a capacity defect.'],
  ['STA-006', 'test-design-techniques',
    'Two techniques give conflicting priorities for the same feature. The analyst should:',
    ['Reconcile them against the risk assessment, which is the tie-breaking authority', 'Use the more formal technique', 'Use both fully regardless of cost', 'Use the faster technique'], 0,
    'Techniques are instruments; risk is the objective they serve.'],
  ['STA-007', 'testing-metrics',
    'Which coverage claim is honest for an exploratory-only test effort?',
    ['Charters completed and areas explored, with explicitly unexplored areas named', 'Percentage of requirements covered', 'Statement coverage', 'A defect-free assertion'], 0,
    'Session-based reporting makes exploratory work accountable without pretending to a coverage number it never measured.'],
  ['STA-008', 'requirements-testing',
    'A requirement is testable but only with a test that would cost more than the feature. The analyst should:',
    ['Report the cost, propose a cheaper partial oracle and let the risk owner decide', 'Test it anyway', 'Skip it silently', 'Declare the requirement untestable'], 0,
    'Cost of verification is legitimate information for the risk owner, and hiding it makes the decision for them.'],
  ['STA-009', 'testing-types',
    'Security testing performed by a Test Analyst (not a specialist) should focus on:',
    ['Access control, input validation and error handling at the functional level', 'Cryptographic algorithm design', 'Kernel exploitation', 'Firmware analysis'], 0,
    'Broken access control and injection are consistently top of the OWASP list and are within functional test reach.'],
  ['STA-010', 'test-design-techniques',
    'A system integrates with five external services. The highest-value analyst-designed tests are around:',
    ['Failure modes of each integration: timeout, malformed response, partial failure', 'The happy path of each integration', 'The UI of the integration screen', 'The logging format'], 0,
    'Happy paths are usually exercised by everyone. Nobody exercises the timeout until production does.'],
  ['STA-011', 'process-analysis',
    'The same defect class recurs across three releases despite being fixed each time. This indicates:',
    ['A missing gate in the process, not a coding problem', 'Careless developers', 'Insufficient regression testing', 'A tooling limitation'], 0,
    'Recurrence of a class, rather than of an instance, is by definition a process signal.'],
  ['STA-012', 'testing-types',
    'Which quality characteristic is most often under-tested in web products and most visible to end users?',
    ['Accessibility', 'Maintainability', 'Portability', 'Modifiability'], 0,
    'Accessibility failures are user-visible, frequently legally binding, and inexpensive to catch with a basic keyboard and contrast pass.'],
  ['STA-013', 'test-documentation',
    'A regression suite has grown to 3,000 cases with an unknown failure yield. The analyst should first:',
    ['Measure which cases have ever failed and correlate with risk before pruning', 'Delete the oldest third', 'Automate all of them', 'Keep them all indefinitely'], 0,
    'Pruning without data removes the wrong cases. Historical yield plus risk is the evidence needed to defend the decision.'],
  ['STA-014', 'test-design-techniques',
    'Boundary value analysis on a date field should include:',
    ['Month ends, leap days, DST transitions and timezone boundaries', 'Only the first and last day of the year', 'Only invalid formats', 'Only the current date'], 0,
    'Calendar arithmetic is where date defects live; the naive numeric boundaries almost never fail.'],
  ['STA-015', 'risks-in-testing',
    'A stakeholder insists a low-risk area receives deep testing. The analyst should:',
    ['Ask what risk they perceive that the model missed, then update the model or explain the trade', 'Comply silently', 'Refuse', 'Escalate immediately'], 0,
    'Stakeholder insistence is usually undocumented risk knowledge. It is an input to the model, not an argument against it.'],
  ['STA-016', 'testing-types',
    'Interoperability testing between your system and a partner system should prioritise:',
    ['Data format, versioning and error semantics at the boundary', 'The partner internal code quality', 'Your own UI', 'The partner staffing'], 0,
    'The contract at the boundary is the only thing both sides can be held to.'],
  ['STA-017', 'defect-management-systems',
    'A defect is closed as "cannot reproduce" for the third time, but users keep reporting it. The analyst should:',
    ['Instrument the flow and collect production evidence to characterise the trigger', 'Close it permanently', 'Raise its severity and reopen unchanged', 'Ask users for better reports'], 0,
    'Reopening the same report without new evidence changes nothing. Observability is the tool for defects that only occur in production conditions.'],
  ['STA-018', 'test-design-techniques',
    'Which is the strongest reason to keep some tests manual in a mature automated suite?',
    ['Human judgement is required for usability, appropriateness and novel exploration', 'Manual tests are cheaper', 'Automation is unreliable', 'Manual tests find more defects per hour'], 0,
    'Automation checks known expectations. Human testing is what discovers expectations nobody wrote down.'],
  ['STA-019', 'testing-metrics',
    'A pass rate of 100% on a suite that has not changed in a year most likely means:',
    ['The suite has stopped providing information', 'The product is defect-free', 'The tests are excellent', 'Coverage is complete'], 0,
    'This is the pesticide paradox observed in the metric: a suite that never fails is no longer a test, it is a ritual.'],
  ['STA-020', 'requirements-testing',
    'The most valuable review comment a Test Analyst can make on a user story is usually:',
    ['Naming a concrete scenario the acceptance criteria do not decide', 'A wording correction', 'A story point suggestion', 'A formatting request'], 0,
    'A concrete undecided scenario forces the requirement gap to be closed while it is still free to close.'],
  ['STA-021', 'test-design-techniques',
    'A feature behaves differently for 12 user roles and 5 subscription tiers. The analyst should:',
    ['Model it as a combination problem and apply pairwise or a classification tree', 'Test all 60 combinations', 'Test only the default role', 'Test only the highest tier'], 0,
    'Sixty combinations is affordable once but not per release; pairwise makes it sustainable, and the risk model decides which full combinations still get tested.'],
  ['STA-022', 'process-optimization',
    'Test analysis effort is best invested where:',
    ['Risk is high and the test basis is weakest', 'Requirements are clearest', 'The code is newest', 'The developers ask for it'], 0,
    'Clear requirements over low risk need the least analysis; the opposite corner needs the most.'],
]);
