import { defineQuestions } from '../define.js';

/**
 * ISTQB Advanced Level - Test Manager (CTAL-TM), asked at the Senior tier.
 * The Performance Review sheet places every Test manager row at the Middle or
 * Senior rung and names ISTQB Advanced Level as a Senior expectation.
 */
export const seniorCtalTmQuestions = defineQuestions('senior', 'istqb-ctal-tm', [
  ['TM-001', 'test-plan',
    'A test policy differs from a test strategy in that the policy:',
    ['States why the organisation tests; the strategy states how, in general terms', 'Is written per project', 'Lists the test cases', 'Defines the tools'], 0,
    'CTAL-TM orders the documents: policy (why) -> strategy (how, organisation-wide) -> test plan (this project) -> level test plans.'],
  ['TM-002', 'test-plan',
    'Which test strategy is characterised by deriving tests from a formal model of the system?',
    ['Analytical / model-based strategy', 'Reactive strategy', 'Consultative strategy', 'Regression-averse strategy'], 0,
    'CTAL-TM lists analytical, model-based, methodical, process-compliant, directed/consultative, regression-averse and reactive strategies. Most real projects blend several.'],
  ['TM-003', 'test-plan',
    'A reactive test strategy is appropriate when:',
    ['The test basis is poor or unavailable and feedback must be fast', 'The system is safety critical with a full specification', 'Regulatory evidence is required', 'The product is stable and unchanged'], 0,
    'Reactive strategies (exploratory, defect-based) respond to the system as delivered rather than to a document that does not exist.'],
  ['TM-004', 'risk-management',
    'In risk-based testing, which activity does the Test Manager own?',
    ['Establishing and running the risk management process across the project', 'Writing every test case', 'Executing the regression suite', 'Reviewing the source code'], 0,
    'The manager owns identification, analysis, mitigation planning and monitoring; the analysts supply the technical and domain judgement.'],
  ['TM-005', 'risk-management',
    'Risk mitigation through testing works by:',
    ['Reducing the likelihood of undetected defects in high-risk areas', 'Reducing the impact of a failure in production', 'Eliminating the risk entirely', 'Transferring the risk to the customer'], 0,
    'Testing addresses the likelihood side of the equation. Impact is reduced by design, redundancy and operational measures.'],
  ['TM-006', 'testing-metrics',
    'Which metric set best supports a go/no-go release decision?',
    ['Risk coverage, open defects weighted by severity and residual risk', 'Test cases executed and hours spent', 'Number of automated tests', 'Lines of code covered'], 0,
    'The decision is about acceptable residual risk, so the metrics must be expressed in risk terms.'],
  ['TM-007', 'testing-metrics',
    'A defect burndown that flattens while new defects keep arriving indicates:',
    ['Discovery is outpacing fixing, so the release date is at risk', 'Testing is complete', 'The product is stable', 'The metric should be discarded'], 0,
    'Arrival and closure rates must be read together; either alone supports the wrong conclusion.'],
  ['TM-008', 'project-estimation',
    'Which estimation technique uses the collective judgement of experts converging over rounds?',
    ['Wideband Delphi', 'Function point analysis', 'Three-point estimation', 'Test point analysis'], 0,
    'Wideband Delphi is a consensus technique; function point and test point analysis are metric-based; three-point is a distribution technique.'],
  ['TM-009', 'project-estimation',
    'Metrics-based estimation is more defensible than expert-based estimation when:',
    ['The organisation has reliable historical data from comparable projects', 'The project is entirely new in domain and technology', 'The team has just been formed', 'No data has been collected'], 0,
    'Without history, metrics-based estimation projects a number from nothing, which is expert judgement with false precision.'],
  ['TM-010', 'team-test-planning',
    'A test manager must plan testing for a distributed team across three time zones. The most important planning decision is:',
    ['Explicit handover, ownership and communication protocols', 'Identical working hours for everyone', 'A single shared test environment', 'One common spoken language only'], 0,
    'Distributed testing fails on ambiguity of ownership far more often than on tooling.'],
  ['TM-011', 'role-distribution',
    'When forming a test team, the Test Manager should consider:',
    ['The mix of skills required by the risks, and the development of each individual', 'Only technical skills', 'Only availability', 'Only cost'], 0,
    'CTAL-TM treats team composition as a risk mitigation decision, not just a staffing one.'],
  ['TM-012', 'people-management',
    'A tester lacks the skills a high-risk area demands. The Test Manager should:',
    ['Pair them with an experienced tester and plan the skill development explicitly', 'Assign the area to someone else permanently', 'Assign it anyway and hope', 'Remove the area from scope'], 0,
    'Pairing mitigates the immediate risk and removes the future one; permanent reassignment mitigates only the first.'],
  ['TM-013', 'process-optimization',
    'TMMi and TPI are examples of:',
    ['Test process improvement models', 'Test design techniques', 'Defect taxonomies', 'Automation frameworks'], 0,
    'TMMi is a staged maturity model; TPI Next is a continuous model with key areas assessed independently.'],
  ['TM-014', 'process-optimization',
    'The IDEAL model for process improvement stands for:',
    ['Initiating, Diagnosing, Establishing, Acting, Learning', 'Identify, Design, Execute, Analyse, Log', 'Investigate, Decide, Evaluate, Adjust, Leave', 'Improve, Deliver, Estimate, Assess, Learn'], 0,
    'The Learning phase is the one most often skipped, which is why organisations repeat the same improvement cycle.'],
  ['TM-015', 'process-optimization',
    'A retrospective produces the same action items every sprint. This most likely means:',
    ['Actions are not being owned, sized and tracked to completion', 'The team lacks ideas', 'Retrospectives are unnecessary', 'The process is already optimal'], 0,
    'An action without an owner and a due date is a wish. Repetition is the symptom.'],
  ['TM-016', 'customer-test-reports',
    'A test progress report to senior management should emphasise:',
    ['Status against objectives, residual risk and decisions required', 'Detailed defect descriptions', 'Test case level results', 'Tool configuration'], 0,
    'Report at the altitude of the decision the reader has to make.'],
  ['TM-017', 'defect-management-systems',
    'Which is a valid reason for a defect management process to include a triage meeting?',
    ['To agree priority and ownership across roles with the full context present', 'To reduce the defect count', 'To assign blame', 'To speed up test execution'], 0,
    'Triage is where product, development and test reconcile severity with business priority in one place.'],
  ['TM-018', 'testing-metrics',
    'Defect Removal Efficiency measures:',
    ['The proportion of defects removed before release', 'The speed of fixing', 'The number of defects per developer', 'The cost per defect'], 0,
    'DRE is a process-effectiveness metric and is one of the few that can justify investment in earlier testing.'],
  ['TM-019', 'risk-management',
    'A project risk materialises: the only test environment is unavailable for two weeks. The Test Manager should first:',
    ['Execute the contingency plan and communicate the schedule impact', 'Wait and see', 'Reduce the test scope silently', 'Ask testers to work overtime later'], 0,
    'The contingency was planned for exactly this. Silent scope reduction converts a schedule problem into a quality problem nobody agreed to.'],
  ['TM-020', 'team-test-planning',
    'Entry criteria for a test level should be enforced because:',
    ['Starting on an unready build wastes effort and produces misleading results', 'They are required by the standard', 'They shorten the schedule', 'They reduce documentation'], 0,
    'Testing an unstable build generates defects about the build rather than about the product.'],
  ['TM-021', 'test-plan',
    'Which is a legitimate reason to tailor a standard test process for a project?',
    ['The project risk profile, lifecycle and regulatory context differ', 'The team prefers fewer documents', 'The deadline is tight', 'The customer has not asked for it'], 0,
    'Tailoring is expected; tailoring justified only by schedule pressure is scope reduction in disguise.'],
  ['TM-022', 'people-management',
    'Which leadership behaviour most improves defect reporting quality across a team?',
    ['Reviewing reports constructively and publishing shared examples of good ones', 'Setting a minimum defect quota', 'Ranking testers by defect count', 'Rejecting weak reports without comment'], 0,
    'Quotas and rankings optimise for volume. Shared exemplars change the standard everyone writes to.'],
  ['TM-023', 'project-estimation',
    'When negotiating a reduced test budget, the Test Manager should present:',
    ['The specific coverage that will be dropped and the risk it exposes', 'A refusal', 'A silent acceptance', 'A uniform reduction across all areas'], 0,
    'Making the trade explicit moves the decision to whoever owns the risk, which is where it belongs.'],
  ['TM-024', 'customer-test-reports',
    'A test summary report at project close should include:',
    ['What was tested, results, residual risk and lessons learned', 'Only the defect count', 'Only the pass rate', 'Only the schedule variance'], 0,
    'The lessons-learned section is what makes the next project cheaper; it is also the first thing cut under pressure.'],
  ['TM-025', 'onboarding-training',
    'A new Test Manager inherits a team with no documented process. The best first move is:',
    ['Observe and baseline the current way of working before changing it', 'Introduce a full standard process immediately', 'Replace the tooling', 'Reassign every role'], 0,
    'Undocumented does not mean absent. Changing an unmeasured process makes any later improvement unprovable.'],
  ['TM-026', 'risk-management',
    'Which statement about risk-based testing is FALSE?',
    ['It guarantees that all high-risk defects will be found', 'It allocates effort proportionally to risk', 'It supports release decisions', 'It requires periodic reassessment'], 0,
    'It improves the odds and makes the trade explicit; it does not remove the possibility of an escaped defect.'],
  ['TM-027', 'process-analysis',
    'The most reliable indicator that a test process improvement worked is:',
    ['A measured change in an outcome metric against the pre-change baseline', 'Positive team sentiment', 'More documentation produced', 'A larger test suite'], 0,
    'Sentiment and volume both move for reasons unrelated to quality.'],
  ['TM-028', 'team-reports',
    'Reporting to a customer that "testing is 80% complete" is weak because:',
    ['Percentage of executed cases says nothing about risk covered or defects open', 'It is too precise', 'It should be a fraction', 'Customers dislike percentages'], 0,
    'Eighty percent of the cases can leave one hundred percent of the highest risk untested.'],
  ['TM-029', 'presale',
    'In a contractual acceptance testing context, the Test Manager must ensure that:',
    ['Acceptance criteria and the evidence required are agreed in writing beforehand', 'Testing is done only by the supplier', 'Only functional tests are run', 'The customer writes all test cases'], 0,
    'Contractual acceptance disputes are almost always about evidence that was never agreed.'],
  ['TM-030', 'test-doc-development',
    'Which standard is commonly referenced for test documentation content?',
    ['ISO/IEC/IEEE 29119', 'ISO 9001 only', 'IEEE 802.11', 'ISO 14001'], 0,
    '29119 replaced IEEE 829 as the reference for test process and documentation templates.'],
  ['TM-031', 'people-management',
    'A senior tester is disengaged after two years on the same regression suite. The most effective response is:',
    ['Give them ownership of a meaningful improvement or a new technical area', 'Increase their workload', 'Move them to another project immediately', 'Ignore it until they raise it'], 0,
    'Autonomy and mastery are what the situation lacks. More of the same work addresses neither.'],
  ['TM-032', 'testing-metrics',
    'Which is the strongest argument for tracking escaped defects by root cause?',
    ['It shows which process gate is failing and where to invest next', 'It identifies which tester missed them', 'It reduces the defect count', 'It satisfies the customer'], 0,
    'Root cause by gate turns a defect list into an improvement backlog.'],
]);
