import { defineQuestions } from '../define.js';

/**
 * Trainee tier, sourced from the "grey" rows of the Performance Review sheet:
 * test artefacts, severity vs priority, defect life cycle, testing types,
 * test design techniques, keeping up with trends, HTML/CSS, mobile platforms,
 * browser architecture, defect reports in English, test execution, daily
 * reporting, test documentation, and reading English documentation.
 */
export const traineePrQuestions = defineQuestions('trainee', 'pr-matrix', [
  // --- test-artifacts -----------------------------------------------------
  ['TR-ART-001', 'test-artifacts',
    'Which artefact describes a single, concrete verification with preconditions, steps and an expected result?',
    ['Test plan', 'Test case', 'Checklist', 'Test policy'], 1,
    'A test case is the smallest executable unit of test documentation: preconditions, steps, test data and an expected result. A checklist only names what to verify; a test plan describes how testing will be organised.'],
  ['TR-ART-002', 'test-artifacts',
    'What is the main difference between a checklist and a set of test cases?',
    ['A checklist lists what to check without prescribing the exact steps', 'A checklist can only be used for regression', 'A checklist must always contain test data', 'A checklist is written only by the test lead'], 0,
    'A checklist is a lightweight list of verification points. It trades step-by-step reproducibility for speed and flexibility, which is why it suits exploratory and smoke testing.'],
  ['TR-ART-003', 'test-artifacts',
    'Which field is NOT part of a well-formed bug report?',
    ['Steps to reproduce', 'Actual result', 'Expected result', 'The name of the developer who should fix it'], 3,
    'Assignment is a workflow decision made in the tracker, not a descriptive attribute of the defect. Naming a developer in the report itself is presumptuous and ages badly.'],
  ['TR-ART-004', 'test-artifacts',
    'A test scenario differs from a test case mainly in that it:',
    ['Describes a user flow at a higher level, without exhaustive step detail', 'Is always automated', 'Contains no expected result at all', 'Can only be executed once'], 0,
    'A test scenario captures an end-to-end flow ("user registers and completes a first purchase"). Test cases underneath it spell out the concrete steps.'],
  ['TR-ART-005', 'test-artifacts',
    'Which of the following belongs in a test plan rather than in a test case?',
    ['Entry and exit criteria for the test phase', 'The exact value typed into the login field', 'The expected HTTP status code', 'The precondition that a user account exists'], 0,
    'Entry/exit criteria, scope, schedule, environments and risks are planning-level concerns. Concrete data and expected results live in test cases.'],
  ['TR-ART-006', 'test-artifacts',
    'Why should a test case have exactly one expected result per step?',
    ['So that a failure points unambiguously at the step that produced it', 'Because tools cannot store more than one', 'To keep the case shorter than one page', 'Because ISTQB forbids more than one'], 0,
    'One assertion per step keeps failure localisation cheap. When a step carries three expectations, a red result tells you almost nothing about what broke.'],

  // --- severity-priority --------------------------------------------------
  ['TR-SEV-001', 'severity-priority',
    'A company logo is misspelled on the home page of a public marketing site. The most defensible classification is:',
    ['Low severity, high priority', 'High severity, low priority', 'High severity, high priority', 'Low severity, low priority'], 0,
    'Nothing is functionally broken, so severity is low. It is on the most visible page of a brand-facing site, so it must be fixed first: priority is high.'],
  ['TR-SEV-002', 'severity-priority',
    'Severity is best defined as:',
    ['The degree of impact the defect has on the system or its users', 'How soon the defect must be fixed', 'How often the defect reproduces', 'How long the fix will take'], 0,
    'Severity measures impact and is normally set by the tester. Priority measures urgency of the fix and is normally set by the product owner or manager.'],
  ['TR-SEV-003', 'severity-priority',
    'An application crashes when a user opens a settings screen that fewer than 0.1% of users ever visit. Reasonable classification:',
    ['High severity, low priority', 'Low severity, high priority', 'Low severity, low priority', 'Severity and priority are always equal'], 0,
    'A crash is high severity by definition. Because the affected path is almost never used, the business may legitimately schedule the fix later, so priority is low.'],
  ['TR-SEV-004', 'severity-priority',
    'Who normally has the final say on a defect priority?',
    ['The product owner or project manager', 'The tester who found it', 'The developer who will fix it', 'The customer support agent'], 0,
    'Priority is a scheduling and business decision. The tester proposes it; the person who owns the backlog decides it.'],
  ['TR-SEV-005', 'severity-priority',
    'Which statement about severity and priority is correct?',
    ['They are independent attributes and any combination is possible', 'High severity always implies high priority', 'Low priority always implies low severity', 'Only one of the two needs to be filled in'], 0,
    'All four combinations occur in practice. Treating them as one field loses the distinction between "how bad" and "how soon".'],
  ['TR-SEV-006', 'severity-priority',
    'A typo appears in an error message shown only to internal admins. Most likely:',
    ['Low severity, low priority', 'High severity, high priority', 'High severity, low priority', 'Low severity, high priority'], 0,
    'Cosmetic, internal-only and non-blocking: low on both axes. It still belongs in the tracker so it can be batched into a text-cleanup task.'],

  // --- defect-lifecycle ---------------------------------------------------
  ['TR-LIFE-001', 'defect-lifecycle',
    'Which status does a defect normally receive when the developer states that the described behaviour is intentional?',
    ['Rejected / Not a bug', 'Deferred', 'Duplicate', 'Reopened'], 0,
    '"Not a bug" (or "Works as designed") means the behaviour matches the requirement. The right response is to challenge the requirement if you disagree, not to reopen the ticket unchanged.'],
  ['TR-LIFE-002', 'defect-lifecycle',
    'A defect marked Fixed fails verification. The tester should:',
    ['Reopen it with the new evidence', 'Create a brand-new defect and close the old one', 'Close it and mention the problem in the daily report', 'Assign it to another developer'], 0,
    'Reopening keeps the history, the discussion and the original context in one place. Filing a duplicate fragments the trail.'],
  ['TR-LIFE-003', 'defect-lifecycle',
    'What does the status "Deferred" mean?',
    ['The defect is real but its fix is postponed to a later release', 'The defect could not be reproduced', 'The defect duplicates an existing one', 'The defect was fixed but not yet verified'], 0,
    'Deferred is an explicit business decision to carry a known defect forward. It should always carry a target release or a review date.'],
  ['TR-LIFE-004', 'defect-lifecycle',
    'Which status closes the life cycle of a defect that was fixed and successfully retested?',
    ['Closed', 'Resolved', 'Verified in progress', 'Assigned'], 0,
    'Typical flow: New -> Assigned -> Fixed/Resolved -> Retested -> Closed. Only the tester should move a ticket to Closed.'],
  ['TR-LIFE-005', 'defect-lifecycle',
    'A defect cannot be reproduced by the developer. The most useful next step for the tester is to:',
    ['Add environment details, build number, logs and a video to the report', 'Immediately close the defect', 'Raise its severity', 'Reassign it to a different developer'], 0,
    'Non-reproducibility is almost always an information gap. Supply the missing context before escalating.'],
  ['TR-LIFE-006', 'defect-lifecycle',
    'Which of these is a valid reason to mark a defect as Duplicate?',
    ['Another open report describes the same root behaviour', 'The defect has low severity', 'The defect was reported by a junior tester', 'The defect is hard to reproduce'], 0,
    'Duplicate means the same underlying defect is already tracked. Link the two so the history stays connected.'],

  // --- testing-types ------------------------------------------------------
  ['TR-TYPE-001', 'testing-types',
    'Smoke testing is best described as:',
    ['A shallow, broad check that the build is stable enough to test further', 'An exhaustive check of one module', 'Testing performed only by the customer', 'Testing that measures response time under load'], 0,
    'Smoke testing answers one question: is this build worth spending a day on? It is broad and shallow by design.'],
  ['TR-TYPE-002', 'testing-types',
    'What is regression testing?',
    ['Re-running tests to confirm that a change did not break existing behaviour', 'Testing that a fixed defect is really fixed', 'Testing the system without any documentation', 'Testing only the newest feature'], 0,
    'Regression testing protects behaviour that already worked. Confirming a specific fix is retesting (confirmation testing), which is a different activity.'],
  ['TR-TYPE-003', 'testing-types',
    'Which pair correctly separates functional from non-functional testing?',
    ['Functional: what the system does. Non-functional: how well it does it', 'Functional: manual. Non-functional: automated', 'Functional: by testers. Non-functional: by developers', 'Functional: before release. Non-functional: after release'], 0,
    'Functional testing checks behaviour against requirements; non-functional testing checks quality characteristics such as performance, usability, security and portability.'],
  ['TR-TYPE-004', 'testing-types',
    'Usability testing primarily evaluates:',
    ['How easily and efficiently real users can achieve their goals', 'How many defects per module exist', 'Whether the code follows the style guide', 'Whether the database schema is normalised'], 0,
    'Usability is a non-functional quality characteristic measured with real users performing real tasks, not by counting defects.'],
  ['TR-TYPE-005', 'testing-types',
    'Sanity testing differs from smoke testing in that it:',
    ['Focuses narrowly on the specific area that was changed', 'Always covers the entire application', 'Is always automated', 'Is performed only in production'], 0,
    'Smoke is broad and shallow across the build; sanity is narrow and deeper, aimed at the area a change touched.'],
  ['TR-TYPE-006', 'testing-types',
    'Which of the following is a NON-functional test type?',
    ['Load testing', 'Integration testing', 'Retesting', 'Acceptance testing'], 0,
    'Load testing measures behaviour under expected volume, a quality characteristic. Integration and acceptance are test levels; retesting is a purpose.'],
  ['TR-TYPE-007', 'testing-types',
    'Exploratory testing is characterised by:',
    ['Simultaneous learning, test design and test execution', 'Executing only pre-written test cases', 'Running only automated checks', 'Testing without any goal or timebox'], 0,
    'Exploratory testing is structured and accountable - usually timeboxed into charters and sessions - it simply designs the tests while running them.'],

  // --- test-design-techniques ---------------------------------------------
  ['TR-TDT-001', 'test-design-techniques',
    'A field accepts integers from 1 to 100. Using boundary value analysis with the two-value approach, which set is correct?',
    ['0, 1, 100, 101', '1, 50, 100', '0, 50, 101', '1, 2, 99, 100'], 0,
    'The two-value approach takes each boundary and its nearest neighbour outside the partition: 0 and 1 at the lower edge, 100 and 101 at the upper edge.'],
  ['TR-TDT-002', 'test-design-techniques',
    'Equivalence partitioning assumes that:',
    ['All values in a partition are processed the same way, so one value represents them all', 'Every possible input must be tested', 'Only invalid inputs need to be tested', 'Partitions must always contain exactly ten values'], 0,
    'The technique reduces test count by exploiting the assumption that a partition behaves uniformly. Boundary value analysis then attacks the edges where that assumption breaks.'],
  ['TR-TDT-003', 'test-design-techniques',
    'A discount applies when a customer is a member AND the basket is over 100. Which technique most directly covers the combinations of these two conditions?',
    ['Decision table testing', 'Boundary value analysis', 'Statement coverage', 'Error guessing'], 0,
    'Decision tables enumerate combinations of conditions and their resulting actions, which is exactly the shape of business rules with several inputs.'],
  ['TR-TDT-004', 'test-design-techniques',
    'State transition testing is the natural fit when:',
    ['The system behaves differently depending on what happened before', 'Inputs are independent numeric ranges', 'There is no specification at all', 'Only performance matters'], 0,
    'State transition testing models states, events, transitions and actions, and is the right tool whenever history changes behaviour (order status, session state, device modes).'],
  ['TR-TDT-005', 'test-design-techniques',
    'Which technique relies primarily on the tester experience rather than on a formal model?',
    ['Error guessing', 'Equivalence partitioning', 'Decision table testing', 'State transition testing'], 0,
    'Error guessing is an experience-based technique. It complements, but does not replace, specification-based techniques.'],
  ['TR-TDT-006', 'test-design-techniques',
    'A registration form has 6 optional checkboxes. Testing all combinations means 64 cases. The pragmatic technique to reduce this is:',
    ['Pairwise (all-pairs) testing', 'Testing every combination anyway', 'Testing only the default state', 'Statement coverage'], 0,
    'Pairwise testing covers every pair of parameter values in a small number of cases, on the empirical grounds that most combinatorial defects involve only two factors.'],
  ['TR-TDT-007', 'test-design-techniques',
    'An age field accepts 18 to 65 inclusive. Which value is a valid equivalence-class representative?',
    ['30', '17', '66', '-1'], 0,
    '30 sits inside the valid partition. 17, 66 and -1 all belong to invalid partitions.'],

  // --- news-trends --------------------------------------------------------
  ['TR-NEWS-001', 'news-trends',
    'Which is the most reliable primary source for the definition of a testing term?',
    ['The ISTQB Glossary', 'The first result of a web search', 'A colleague recollection', 'A vendor marketing page'], 0,
    'The ISTQB Glossary is the maintained, versioned reference the industry actually agrees on. Vendor pages define terms to fit their product.'],
  ['TR-NEWS-002', 'news-trends',
    'A new tool is proposed for the team. The most professional first step is to:',
    ['Run a small, timeboxed pilot on a real task and compare it against the current tool', 'Adopt it because it is popular', 'Reject it because the current tool works', 'Wait until the customer asks for it'], 0,
    'A bounded pilot produces evidence. Both blind adoption and blind rejection substitute opinion for evidence.'],
  ['TR-NEWS-003', 'news-trends',
    'Which of these is a recognised, vendor-neutral certification scheme for testers?',
    ['ISTQB', 'AWS Certified Developer', 'PMP', 'CCNA'], 0,
    'ISTQB is the international, vendor-neutral certification body for software testing. The others certify cloud, project management and networking respectively.'],
  ['TR-NEWS-004', 'news-trends',
    'Keeping up with trends is part of the Performance Review because:',
    ['Testing practice and tooling change, and stale practice quietly lowers quality', 'Certificates are collected for their own sake', 'Managers need something to measure', 'It replaces hands-on experience'], 0,
    'The competency exists to keep practice current. It is assessed by what a tester brings back into the team, not by how many articles they read.'],
  ['TR-NEWS-005', 'news-trends',
    'You read that a technique guarantees "100% bug-free software". The correct professional reaction is:',
    ['Treat the claim as false: exhaustive testing is impossible', 'Adopt it immediately', 'Forward it to the customer', 'Add it to the test plan as a goal'], 0,
    'One of the seven testing principles states that exhaustive testing is impossible, so absence of defects can never be proven by testing.'],

  // --- html-css -----------------------------------------------------------
  ['TR-HTML-001', 'html-css',
    'Which HTML attribute is most commonly used by automated tests to locate an element reliably?',
    ['A dedicated data-testid attribute', 'The class attribute', 'The inline style attribute', 'The title attribute'], 0,
    'Classes and styles change whenever design changes. A dedicated test id is stable by contract, which is why teams add one specifically for automation.'],
  ['TR-HTML-002', 'html-css',
    'What does the CSS selector ".btn.primary" match?',
    ['Elements that have both the btn and primary classes', 'Elements with the btn class inside elements with the primary class', 'Elements with either class', 'An element with id btn and class primary'], 0,
    'Chained class selectors with no space mean "all of these classes on the same element". A space would mean a descendant relationship.'],
  ['TR-HTML-003', 'html-css',
    'Which tag pair is semantically correct for a clickable navigation link?',
    ['<a href="...">', '<div onclick="...">', '<span role="link">', '<button href="...">'], 0,
    'An anchor with href is focusable, keyboard-operable and announced as a link by screen readers, all for free. The others reimplement that badly or not at all.'],
  ['TR-HTML-004', 'html-css',
    'The alt attribute on an <img> exists primarily to:',
    ['Describe the image for assistive technology and when the image fails to load', 'Improve the image resolution', 'Set the image width', 'Cache the image'], 0,
    'alt is an accessibility and resilience feature. A missing or meaningless alt is a genuine, reportable accessibility defect.'],
  ['TR-HTML-005', 'html-css',
    'Which CSS property would you check first when an element is present in the DOM but invisible on screen?',
    ['display / visibility / opacity', 'font-family', 'cursor', 'letter-spacing'], 0,
    'display:none, visibility:hidden and opacity:0 are the three usual causes. They also behave differently for automation: display:none removes the element from layout entirely.'],
  ['TR-HTML-006', 'html-css',
    'What is the difference between an id and a class in HTML?',
    ['An id must be unique in the document; a class may repeat', 'A class must be unique; an id may repeat', 'Both must be unique', 'Neither has any uniqueness rule'], 0,
    'Duplicate ids are invalid HTML and a common cause of flaky locators, because tools then match the first occurrence non-deterministically.'],

  // --- mobile-platforms ---------------------------------------------------
  ['TR-MOB-001', 'mobile-platforms',
    'Which file format is the installable package for an Android application?',
    ['.apk (or .aab for distribution)', '.ipa', '.exe', '.dmg'], 0,
    'APK is the Android package; AAB is the publishing format Google Play expects. IPA is the iOS equivalent.'],
  ['TR-MOB-002', 'mobile-platforms',
    'A hybrid mobile application is best described as:',
    ['A web application wrapped in a native shell', 'An application written twice, once per platform', 'An application that runs only offline', 'An application distributed outside the stores'], 0,
    'Hybrid apps render web content inside a native container (WebView), which is why they often share UI defects with the mobile web version.'],
  ['TR-MOB-003', 'mobile-platforms',
    'Which check is specific to mobile testing and has no direct desktop equivalent?',
    ['Behaviour on an incoming call or push interruption', 'Verifying an error message', 'Checking a mandatory field', 'Validating a date format'], 0,
    'Interrupt testing - calls, notifications, low battery, network switch, backgrounding - is a mobile-specific category driven by the platform lifecycle.'],
  ['TR-MOB-004', 'mobile-platforms',
    'Why must a mobile tester care about the app being sent to the background?',
    ['The OS may kill or restore the process, and unsaved state is often lost', 'Backgrounding is impossible on modern phones', 'It only affects battery consumption', 'It only matters for games'], 0,
    'Android and iOS both reclaim memory from backgrounded apps. State restoration bugs are among the most common and most user-visible mobile defects.'],
  ['TR-MOB-005', 'mobile-platforms',
    'Device fragmentation is a bigger testing problem on Android than on iOS mainly because:',
    ['Many manufacturers ship many OS versions, screen sizes and custom skins', 'Android has no emulators', 'iOS apps are never updated', 'Android does not support automation'], 0,
    'The combination matrix on Android is far larger, which is why device-cloud testing and a prioritised device list matter so much.'],
  ['TR-MOB-006', 'mobile-platforms',
    'Which is a purely mobile non-functional concern?',
    ['Battery and data consumption', 'Response time', 'Security', 'Accessibility'], 0,
    'The other three matter everywhere. Battery drain and cellular data usage are constraints specific to a device carried on a person.'],

  // --- browser-architecture -----------------------------------------------
  ['TR-BROW-001', 'browser-architecture',
    'What is the practical difference between localStorage and sessionStorage?',
    ['sessionStorage is cleared when the tab closes; localStorage persists', 'localStorage is sent with every request', 'sessionStorage is shared across all tabs', 'localStorage has no size limit'], 0,
    'Both are per-origin key/value stores. Scope is the difference: sessionStorage is per tab and dies with it; localStorage survives restarts.'],
  ['TR-BROW-002', 'browser-architecture',
    'Which storage mechanism is automatically attached to every matching HTTP request?',
    ['Cookies', 'localStorage', 'sessionStorage', 'IndexedDB'], 0,
    'Only cookies are transmitted automatically by the browser, which is exactly why they carry session tokens and why CSRF exists.'],
  ['TR-BROW-003', 'browser-architecture',
    'The HttpOnly flag on a cookie means:',
    ['JavaScript cannot read the cookie', 'The cookie is sent only over HTTP, never HTTPS', 'The cookie never expires', 'The cookie is shared across domains'], 0,
    'HttpOnly removes the cookie from document.cookie, which blunts token theft via cross-site scripting. Secure is the flag that requires HTTPS.'],
  ['TR-BROW-004', 'browser-architecture',
    'A hard refresh (Ctrl+Shift+R) differs from a normal refresh because it:',
    ['Bypasses the browser cache and re-downloads resources', 'Clears all cookies', 'Restarts the browser', 'Opens the page in a new tab'], 0,
    'Hard refresh ignores cached assets. It is the first thing to try when a fix is deployed but the old bundle is still being served.'],
  ['TR-BROW-005', 'browser-architecture',
    'Which browser devtools tab would you open first to check whether the front end actually sent a request and what came back?',
    ['Network', 'Elements', 'Console', 'Sources'], 0,
    'The Network tab shows the request, its headers, payload, status and timing - the fastest way to decide whether a defect is front-end or back-end.'],
  ['TR-BROW-006', 'browser-architecture',
    'The DOM is:',
    ['The in-memory tree the browser builds from the HTML, which scripts can change', 'The HTML file stored on the server', 'The CSS rules of a page', 'The browser network cache'], 0,
    'Because the DOM is live, what you see in the Elements panel can differ from the source HTML. That difference explains many "the markup is right but the page is wrong" reports.'],

  // --- defect-reports-en --------------------------------------------------
  ['TR-REP-001', 'defect-reports-en',
    'Which bug report title is the most useful?',
    ['Checkout: order total ignores the applied promo code on Safari 17',
     'Bug in checkout',
     'It does not work!!!',
     'Please fix urgently, customer is angry'], 0,
    'A good title states area, observed behaviour and, when relevant, the condition. It should be readable and searchable without opening the ticket.'],
  ['TR-REP-002', 'defect-reports-en',
    'A defect report must always let a reader answer one question above all others:',
    ['How do I reproduce this?', 'Who is to blame?', 'How long will the fix take?', 'Which sprint is it in?'], 0,
    'Reproducibility is the report core value. Everything else is metadata that can be added later.'],
  ['TR-REP-003', 'defect-reports-en',
    'Which sentence is the better "Actual result" line?',
    ['The page returns HTTP 500 and no order is created',
     'The page is broken',
     'Nothing happens, probably a back-end issue',
     'Same as yesterday'], 0,
    'The actual result should be observable and specific. Diagnosis ("probably back-end") is a hypothesis, not an observation, and belongs in a comment.'],
  ['TR-REP-004', 'defect-reports-en',
    'Why should environment details (build, OS, browser, device) always be in the report?',
    ['Many defects only reproduce on a specific combination', 'To make the report longer', 'Because the tracker requires it', 'To prove the tester did the work'], 0,
    'Environment is often the difference between "cannot reproduce" and a fix in an hour.'],
  ['TR-REP-005', 'defect-reports-en',
    'The best evidence to attach to a UI defect that appears only intermittently is:',
    ['A screen recording plus console and network logs', 'A single screenshot', 'A verbal description', 'The test case id only'], 0,
    'Intermittent defects need timing context. A recording paired with logs lets a developer align what was seen with what the system did.'],
  ['TR-REP-006', 'defect-reports-en',
    'Which of the following makes a defect report harder, not easier, to act on?',
    ['Reporting three unrelated problems in one ticket', 'Numbering the reproduction steps', 'Stating the expected result explicitly', 'Adding the build number'], 0,
    'One defect per report. Bundled tickets cannot be assigned, prioritised, fixed or closed independently.'],

  // --- test-execution -----------------------------------------------------
  ['TR-EXEC-001', 'test-execution',
    'While executing a ready test case, the actual result differs from the expected result, but you believe the expected result is outdated. You should:',
    ['Mark the case Failed and raise the question with the analyst or product owner', 'Silently pass the case', 'Edit the expected result yourself and pass it', 'Skip the case'], 0,
    'Never quietly change the oracle. Record what you observed, then get the requirement clarified; if it changed, the case is updated deliberately and traceably.'],
  ['TR-EXEC-002', 'test-execution',
    'A test case is Blocked when:',
    ['It cannot be executed because of an external obstacle such as a broken environment', 'It fails on the last step', 'It takes longer than estimated', 'It has no test data'], 0,
    'Blocked is distinct from Failed: it means the case never got a chance to produce a verdict. Mixing the two corrupts the pass-rate metric.'],
  ['TR-EXEC-003', 'test-execution',
    'What should a tester do before starting execution on a new build?',
    ['Confirm the build number and environment, then run smoke checks', 'Immediately start the longest test suite', 'Close all previous defects', 'Rewrite the test cases'], 0,
    'Verifying what you are testing, and that it is stable enough to test, prevents a whole day of results being attributed to the wrong build.'],
  ['TR-EXEC-004', 'test-execution',
    'During execution you notice a defect that is outside the scope of the case you are running. You should:',
    ['Report it as a separate defect and continue the case', 'Ignore it because it is out of scope', 'Stop and rewrite the test suite', 'Mark the current case as Failed'], 0,
    'Observations outside the current case are still valuable. Report them separately so the current case keeps a truthful verdict.'],
  ['TR-EXEC-005', 'test-execution',
    'Test execution results should be recorded:',
    ['As they happen, per case, with evidence for failures', 'At the end of the sprint from memory', 'Only when everything passes', 'Only for automated tests'], 0,
    'Results recorded later are results reconstructed, and reconstruction loses exactly the details that make a failure diagnosable.'],
  ['TR-EXEC-006', 'test-execution',
    'A test case passes on your machine but fails on a colleague machine. The first thing to compare is:',
    ['Environment, build and test data', 'Personal preferences', 'Typing speed', 'Screen resolution only'], 0,
    'Environment, build version and data state explain the overwhelming majority of "works on my machine" cases.'],

  // --- daily-reports ------------------------------------------------------
  ['TR-DAY-001', 'daily-reports',
    'The most useful daily status report from a tester contains:',
    ['What was tested, results, blockers and what is planned next', 'The number of hours worked', 'A list of all open defects in the project', 'A copy of the test plan'], 0,
    'A status report exists so that someone else can make a decision. Progress, results, blockers and the next step are the four things a decision needs.'],
  ['TR-DAY-002', 'daily-reports',
    'You are blocked by a broken test environment. When should this appear in your report?',
    ['Immediately, as soon as it blocks you', 'In the weekly summary', 'Only if it lasts more than two days', 'Only if the customer asks'], 0,
    'Blockers lose value with delay. Reporting one on Friday that started on Monday has already cost the project four days.'],
  ['TR-DAY-003', 'daily-reports',
    'Which sentence belongs in a status report rather than in a defect report?',
    ['Smoke suite executed on build 1.4.2: 28 passed, 2 failed, 1 blocked', 'Steps to reproduce: 1. Open cart...', 'Expected result: total is recalculated', 'Severity: Major'], 0,
    'Aggregated progress belongs in the status report; per-defect detail belongs in the tracker. Repeating the detail in both places guarantees they will diverge.'],
  ['TR-DAY-004', 'daily-reports',
    'A monthly report for a customer should be written:',
    ['In terms of product quality and risk, not raw tester activity', 'As a list of every executed test case', 'As a copy of the daily reports concatenated', 'Only in bullet points with no numbers'], 0,
    'A customer buys confidence in the product. Activity logs answer a question they did not ask.'],
  ['TR-DAY-005', 'daily-reports',
    'Reporting "I tested the application today" is weak mainly because:',
    ['It states no scope, no result and no risk', 'It is too short', 'It is in the wrong tense', 'It does not mention the tool used'], 0,
    'The sentence cannot support any decision. Scope, outcome and risk are the minimum content of a useful status line.'],

  // --- test-documentation -------------------------------------------------
  ['TR-DOC-001', 'test-documentation',
    'A good test case is best described as:',
    ['Independent, repeatable and unambiguous', 'As long as possible', 'Written only for automation', 'Dependent on the previous case'], 0,
    'Independence is what allows cases to be reordered, parallelised and executed by someone who did not write them.'],
  ['TR-DOC-002', 'test-documentation',
    'What is traceability in test documentation?',
    ['A recorded link between requirements and the tests that cover them', 'Numbering the test cases sequentially', 'Storing documents in one folder', 'Keeping a change log of the test plan'], 0,
    'Traceability is what lets you answer "is this requirement covered?" and "what must be retested if this requirement changes?".'],
  ['TR-DOC-003', 'test-documentation',
    'A mind map is a good choice for test documentation when:',
    ['You need to explore and communicate coverage quickly at an early stage', 'You need step-by-step reproducibility for an auditor', 'You need to store execution results', 'You need to run tests automatically'], 0,
    'Mind maps excel at structure and coverage conversations. They are a poor substitute when detailed, evidenced steps are contractually required.'],
  ['TR-DOC-004', 'test-documentation',
    'Which is the strongest argument for keeping test cases short?',
    ['Short cases fail for one identifiable reason', 'Short cases are faster to type', 'Short cases need no review', 'Short cases can skip the expected result'], 0,
    'Diagnosability is the goal. A 40-step case that fails tells you almost nothing about where the product broke.'],
  ['TR-DOC-005', 'test-documentation',
    'Preconditions in a test case exist to:',
    ['State the system and data state required before step 1', 'List the defects found earlier', 'Name the author', 'Record the execution date'], 0,
    'Preconditions make a case reproducible by someone who is not you, on a machine that is not yours.'],
  ['TR-DOC-006', 'test-documentation',
    'Test documentation that is never updated after the first release is:',
    ['A liability, because it reports coverage the product no longer has', 'Still fully valuable', 'Only a minor problem', 'Preferable, since it is stable'], 0,
    'Stale documentation is worse than none: it produces confident, wrong answers about coverage.'],

  // --- english-reading ----------------------------------------------------
  ['TR-ENG-001', 'english-reading',
    'A requirement says: "The system shall lock the account after three consecutive failed login attempts." Which test is directly implied?',
    ['Fail login three times in a row and verify the account is locked', 'Fail login twice and verify a warning email', 'Log in successfully and verify the session length', 'Verify the password reset link expires'], 0,
    '"Shall" marks a mandatory requirement. The condition (three consecutive failures) and the outcome (lock) map straight onto one test.'],
  ['TR-ENG-002', 'english-reading',
    'In requirements written in English, the word "should" typically indicates:',
    ['A recommendation rather than a mandatory requirement', 'A mandatory requirement', 'A defect', 'A deprecated feature'], 0,
    'In RFC 2119 style, "shall"/"must" are mandatory and "should" is recommended. The distinction changes whether a deviation is a defect.'],
  ['TR-ENG-003', 'english-reading',
    'A ticket states "Expected: the modal is dismissed on Esc". "Dismissed" here means:',
    ['Closed', 'Disabled', 'Rejected by the server', 'Moved to the background'], 0,
    'In UI vocabulary, dismissing a modal means closing it without completing its action.'],
  ['TR-ENG-004', 'english-reading',
    'Release notes say a feature is "deprecated". The correct reading is:',
    ['It still works but is discouraged and will be removed later', 'It has already been removed', 'It is broken', 'It is newly added'], 0,
    'Deprecated means scheduled for removal. Tests should still cover it, and its removal date should be tracked.'],
  ['TR-ENG-005', 'english-reading',
    'A spec says a value is "mandatory unless the user is a guest". Which case must exist in your suite?',
    ['A guest user for whom the value may be empty', 'Only a registered user with the value filled', 'Only an empty value for every user', 'No case is needed'], 0,
    'The "unless" clause defines a second equivalence partition. Testing only the main clause leaves half the rule uncovered.'],
]);
